### ISSUE TITLE
Plot entry/leave notification and VanishNoPacket

### ISSUE THREAD

**Issue by EvilOlaf** [IntellectualCrafters/PlotSquared#100]
A plot owner gets a entry or leave notification if a vanished player enters or leaves their plots.
As workaround an extra permission node may be nice to disable these notifications at all.

**Comment by boy0001** [comment]
Yay, issue #100 !!!
 - This might be included in the next major update.

**Comment by boy0001** [comment]
Added:
plots.flag.notify-enter.bypass

**Comment by EvilOlaf** [comment]
So if player X which has the permission to vanish has these flags you posted above and player Y which owns a plot with the notify flags enabled, he (player Y) will not receive a notification that someone entered his plot.

Please correct me if I'm wrong.

**Comment by boy0001** [comment]
Yes, if you have the bypass permissions, then any owner of a plot will not know if you enter or leave. Doing it any other way would be stupid. 

As for documentation... feature creeping is so much more fun!

**Comment by boy0001** [comment]
k, I finished documenting ALL OF THE FLAGS. It was so boring, but there's now documentation.

**Comment by EvilOlaf** [comment]
Great. 

I believe you test documentation is a boring job, but what's the reason for new features is nobody knows how to use them?

**Comment by boy0001** [comment]
Figuring it out can be fun. It's like a puzzle game and plot management system all in one.

**Comment by EvilOlaf** [comment]
Which were the most I think :D
