### ISSUE TITLE
%s in Title

### ISSUE THREAD

**Issue by jyhsu2000** [IntellectualCrafters/PlotSquared#101]
In `v2.5.11`
When I entry a plot and it shows title.
There is a `%s` in title.
It doesn't replace with plot ID.
![title](http://i.imgur.com/tV9V2NC.png)

**Comment by boy0001** [comment]
Open your translations file `PlotSquared.use_THIS.yml` and replace `title_entered_plot: "You entered plot %s"` with `title_entered_plot: "You entered plot %world%;%x%;%z%"`

**Comment by jyhsu2000** [comment]
Thanks.
It works.

But I found another bug.
I modify translation file when server run.
I use `/plot reload` and get message `[Plot]The translation files has been reloaded`.
But it doesn't take effect.
And when I stop server, the translation file auto restore to the version when I startup server.

**Comment by boy0001** [comment]
Yep, the translations are definitely an issue. I'll close this now, and add this info to #98
