### ISSUE TITLE
[v2.5.11] Plot Auto Clear gone MAD

### ISSUE THREAD

**Issue by brunyman** [IntellectualCrafters/PlotSquared#102]
Hi,

I'v set this in the config:

clear:
  auto:
    enabled: true
    days: 30
  'on':
    ban: false

and i was expecting the auto plot clear to take place after 30 days of inactivity, but after a short amount of time, less then few hours most plots got cleared, i think they are cleared at 30 min of inactivity, we use sqlite for storage. Right now i disabled the auto clear to see if this was indeed the issue, but as the logs say looks like plots got cleared for inactivity or "expired"

[09:29:38] [Server thread/INFO]: [0;31;1mDeleted expired plot: 0;0[m
[09:29:38] [Server thread/INFO]: [0;36;22m - World: world_creative[m
[09:29:38] [Server thread/INFO]: [0;36;22m - Owner: Lolatanesa[m

We really need this auto clear feature, as it makes the server maintenance free and no intervention needed to clear old plots, as we also use a world border and a ram drive.

**Comment by boy0001** [comment]
Are you using `offline` or `online` mode UUIDs?

**Comment by brunyman** [comment]
offline UUIDs

**Comment by boy0001** [comment]
`I have these settings

clear:
auto:
enabled: true
days: 60

and a players plot was deleted

[06:34:29] [Server thread/INFO]: Deleted expired plot: -18;-53
[06:34:29] [Server thread/INFO]: - World: plotme_donor
[06:34:29] [Server thread/INFO]: - Owner: SuperBiz

I have a bungee plugin that tracks last logins, his last login was january 1st. Also, the last modified date on his playerdata file for the creative server was also january 1st. January 1st was 23 days ago not 60 so this is obviously a major bug` - PhanaticD

**Comment by boy0001** [comment]
aabbd851ec2c40e4119177e8fdba9221e2bfe28a - will help with safely testing the plot expiry system in future.

I've also added some more checks for old plot removal which may or may not fix the issue.

**Comment by brunyman** [comment]
ok, we will test it when you release the update

**Comment by boy0001** [comment]
Should be fixed now.
