### ISSUE TITLE
Old plot deletion not working properly

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualCrafters/PlotSquared#104]
I have these settings

 clear:
   auto:
     enabled: true
     days: 60

and a players plot was deleted

[06:34:29] [Server thread/INFO]: Deleted expired plot: -18;-53
[06:34:29] [Server thread/INFO]:  - World: plotme_donor
[06:34:29] [Server thread/INFO]:  - Owner: SuperBiz

I have a bungee plugin that tracks last logins, his last login was january 1st. Also, the last modified date on his playerdata file for the creative server was also january 1st. January 1st was 23 days ago not 60 so this is obviously a major bug

**Comment by Uncleleech** [comment]
See: https://github.com/IntellectualCrafters/PlotSquared/issues/102

I'm sure boy001 is going to ask; online or offline UUIDS?

**Comment by boy0001** [comment]
merging with #102
