### ISSUE TITLE
Roadschematics

### ISSUE THREAD

**Issue by AgentLV** [IntellectualCrafters/PlotSquared#105]
Now this happens: 
http://abload.de/img/2015-01-23_16.17.443lp9s.png

My old issue regarding this bug:
https://github.com/IntellectualCrafters/PlotSquared/issues/96

**Comment by boy0001** [comment]
When creating the road schematic, you need to create the entire road on the north and northwest sides of the plot.

It looks like you are only creating half of the road.

**Comment by EvilOlaf** [comment]
For a better understanding of the road schematics behavior you may - as I already brought you close ingame ;) - edit the generated default schematics by hand.

Therefore just create a fresh plot world with the road width as you wish and save the road schematics with "CreateRoadSchematic".
After that you will find in a subfolder of your PlotSquared plugin directory two schematics: sideroad and intersection.
Copy those into your schematics folder of WorldEdit and paste them somewhere.
As long as you keep the dimensions at the X and Z axis you should be able to edit freely till it fits your imagination.
Save them again with same name (you may backup the original schematics before) and recopy them to the subfolder of PlotSquared. Then either regen all roads or recreate the whole world.

Keep in mind that any light-spreading blocks won't work till you change the light somehow in an area close to the light source (place a torch, touch the glowstone/sea lantern, whatever....). You will notice when you see.

**Comment by AgentLV** [comment]
Thx Krauti(EvilOlaf), but it worked with "CreateRoadSchematic". Like boy0001 wrote, I only built half of the road, which was reason why it wasn't working.
