### ISSUE TITLE
Itemframe permissions

### ISSUE THREAD

**Issue by AgentLV** [IntellectualCrafters/PlotSquared#111]
Moderators on my server have these permissions:
plots.admin.build.*
plots.admin.destroy.*
plots.admin.interact.*
plots.admin.projectile.*

but they cannot destroy the content of the itemframes, but everything else. If I give them plots.admin the can also destroy the content in the itemframes. It's just a minor bug, because the Mods could also just destroy the block and the itemframe would disapear.

**Comment by boy0001** [comment]
Try "plots.admin.pve.*"

**Comment by boy0001** [comment]
Side note: I need to document this stuff a bit more.

**Comment by AgentLV** [comment]
Thx!

**Comment by EvilOlaf** [comment]
*signed*
