### ISSUE TITLE
Pistons can shift blocks  across the plot borders

### ISSUE THREAD

**Issue by EvilOlaf** [IntellectualCrafters/PlotSquared#112]
Players are able to shift a block with a piston on the street. When the block is shifted there it is oblivious that the player can not break it anymore.
PS 2.5.11 @ Spigot

**Comment by boy0001** [comment]
This is an issue with the bukkit event system, there is no known fix yet.
See #4

**Comment by EvilOlaf** [comment]
Sad to hear.
