### ISSUE TITLE
Quickshop not working on plots

### ISSUE THREAD

**Issue by EvilOlaf** [IntellectualCrafters/PlotSquared#115]
Enhancement

Users which have no helper or trust status on a plot can not use quickshop chests to buy or sell items. Pex debug tells me that the plugin asks for plots.admin.interact.other which is obviously not present on common players without any special rights.

Therefore QuickShops cannot be used in a Plotworld seriously.

It would be very nice if this could be fixed.

Maybe this could be combined  with https://github.com/IntellectualCrafters/PlotSquared/issues/94

**Comment by boy0001** [comment]
merged with #94
