### ISSUE TITLE
Teleport delay for plots home

### ISSUE THREAD

**Issue by EvilOlaf** [IntellectualCrafters/PlotSquared#116]
Enhancement

On pvp servers it is very common to add a teleport delay to prevent players from escaping fights by teleporting home or to the spawn. This is mostly done by the Essentials teleport delay timer.
Unfortunately PlotSquared does not offer an option to slow p/plot/plots home down.

As a workaround I fixed that by adding a warmup with MyCommand, but honestly this solution does not work pretty well for me.

Thanks for reading.

**Comment by boy0001** [comment]
It will be added in version 2.7 (if not in the first update, it will be soon after)

**Comment by EvilOlaf** [comment]
And a bypass permission node please <3

**Comment by boy0001** [comment]
ofc

**Comment by boy0001** [comment]
Bypass: plots.teleport.delay.bypass

**Comment by boy0001** [comment]
TODO: Cancel on damage.

**Comment by boy0001** [comment]
added: 5f9dce1a075a51786cc2b8f49d76573bd16c6f01
