### ISSUE TITLE
[v2.6.1] /p flag command

### ISSUE THREAD

**Issue by jyhsu2000** [IntellectualCrafters/PlotSquared#118]
`Usage: /plot flag <set|remove|add|list|info>`

When I use `/p flag list`
It shows `Usage: /plot flag list`
It can not show flags of plot

When I use `/p flag info`
It shows `Usage: /plot flag <set|remove|add|list|info>`
There even no `case "info"` in FlagCmd.java
Doesn't implement yet ?

**Comment by boy0001** [comment]
`Info` hasn't been implemented, however it will show documentation on each flag, and what it does.
`/p flag list` should just show a list of potential flags, for a list of flags in the plot, use `/plot info` or `/plot info flags`

**Comment by EvilOlaf** [comment]
+1 for documentation :>
