### ISSUE TITLE
[v2.6.1] message of no permission

### ISSUE THREAD

**Issue by jyhsu2000** [IntellectualCrafters/PlotSquared#119]
Some messages of lacking permission only shows to someone has permission.
Following is some of example
- plots.admin.destroy.unowned
- plots.admin.destroy.road
- plots.admin.interact.unowned
- plots.admin.interact.road

Maybe some wrong code in `PlayerEvents.java`
Line 256, 268, 276, 507, 517, 525
`!`(Not Sign) is missing in if when call `PlotMain.hasPermission()`

Just static analysis, I'm not sure if it works.

**Comment by boy0001** [comment]
The messages have been fixed. As for `PlotMain.hasPermission()`, a null player argument is used if the command is sent from console (that way the same code works with players and console)
