### ISSUE TITLE
Plot undo command

### ISSUE THREAD

**Issue by boy0001** [IntellectualCrafters/PlotSquared#12]
Undo plot clearing up to 20s after you accidentally cleared you plot
OR
Add a confirm command for plot clearing (config option)

**(Please comment to let us know your preference)**

**Comment by EvilOlaf** [comment]
I think this is unneeded effort to integrate this feature. Just add a security query to ask the clearing player if he is sure to do so.

**Comment by boy0001** [comment]
```
OR
Add a confirm command for plot clearing (config option)
```

Is currently being added: b20f13bc582110263e9fbe7df78c38d75f111363

**Comment by boy0001** [comment]
Added
