### ISSUE TITLE
Standalone PlotSquared generator

### ISSUE THREAD

**Issue by boy0001** [IntellectualCrafters/PlotSquared#127]
Release a standalone version of the PlotSquared generator
 - For servers not wishing to use the PlotSquared plot management system but only the world generation

**Comment by EvilOlaf** [comment]
Interesting.
Well then have fun adding the regions in worldguard each and every one for itself :D

**Comment by boy0001** [comment]
As an example of demand for standalone plot generators:
 - http://dev.bukkit.org/bukkit-plugins/plots-generator/
 - http://dev.bukkit.org/bukkit-plugins/infiniteplots/

There are also many plot management systems out there that people may prefer:
 - WorldGuard
 - PlotManager
 - PlotMe
 - SimplePlot
 - Plotty
 - Plotz
and probably a few more.

This way if people aren't using the PlotSquared management system, they can at least be using the advanced functionality offered with the PlotSquared generator.

**Comment by boy0001** [comment]
Added: https://github.com/boy0001/PlotSquared-SG
 - Create a plotworld without any plot management system
 - Optional PlotMe hook
