### ISSUE TITLE
Roads - Min and Max height

### ISSUE THREAD

**Issue by recon88** [IntellectualCrafters/PlotSquared#128]
I would like to be able to set a "min-height" and "max-height" for roads so it doesn't generate them from bottom to the config value "height".  
E.g.: I set min and max to 64 and it only builds the road on that single layer.

**Comment by boy0001** [comment]
Could you please explain the benefit of this? If you are looking for faster road regeneration, this just adds extra checks the plugin needs to do.

**Comment by recon88** [comment]
For me it would be just the visual change so people don't see wood/stone or whatever the road is set to :)

**Comment by boy0001** [comment]
Sorry, I'm not going to add this, as it's not something most servers would ever use. You can obtain the same result by setting the road height to 0, and using schematic generation for your custom roads.

**Comment by recon88** [comment]
I would use a schematic but there's the other issue where it doesn't generate schematic roads in new chunks.
