### ISSUE TITLE
Weird biome issues

### ISSUE THREAD

**Issue by recon88** [IntellectualCrafters/PlotSquared#130]
I'm having weird biome issues. One plot has mixed desert and plains. If I change it to something else and relog, it's fine. But if I restart the server, the changes are gone and it's all weird again.
Did anyone encounter that issue already?

http://i.imgur.com/OyN5HsO.png

**Comment by boy0001** [comment]
Restarting the server doesn't regenerate any chunks, perhaps it's an issue with the server not being able to save the biome data for those specific chunks. What tool are you using to edit the biome?

**Comment by recon88** [comment]
I'm just using the built-in /p set biome <biome>
That didn't work. Tried WorldEdit's setbiome, didn't work.

**Comment by boy0001** [comment]
I would guess that the chunks are partially corrupt. Please try to regenerate the world as @EvilOlaf suggested.

You don't need multiverse, just delete the region files for that world while the server is stopped. Anything you want to save you will need to save as a schematic beforehand. Or you could just live with the biome issue.

**Comment by recon88** [comment]
For future reference (if you have WorldEdit installed):
Just mark one layer with //pos1 and //pos2 (at y:256) and use //regen
This will regenerate the chunk without deleting the buildings. Fixes biomes and still works after restarting the server :)
