### ISSUE TITLE
Error MySQL

### ISSUE THREAD

**Issue by Reymouth** [IntellectualCrafters/PlotSquared#134]
I use MySQL storage and when I disable the feature "title" in the configuration, it is impossible to write plugins in MySQL tables.

The error is: http://pastebin.com/RKBKFaRY

**Comment by boy0001** [comment]
Titles has nothing to do with MySQL being unreachable. You could try resetting the wait timout:

SET GLOBAL wait_timeout =28800;

**Comment by Reymouth** [comment]
Problem solved, thank you

**Comment by boy0001** [comment]
cool.
