### ISSUE TITLE
Filter plots list by player name

### ISSUE THREAD

**Issue by EvilOlaf** [IntellectualCrafters/PlotSquared#137]
Enhancement

Sometimes as staff member you need a list of all plots a player owns or can build on.
So my suggestion is to add a new parameter to the plots list command to something like

```
/plot list <mine / player / shared / world / all> [player name]
```

**Comment by boy0001** [comment]
added: cca903bf8de4e2969e5786f98897035464bc67c2

**Comment by EvilOlaf** [comment]
Yay :D
