### ISSUE TITLE
Permission for redstone mechanics

### ISSUE THREAD

**Issue by ziutekkk** [IntellectualCrafters/PlotSquared#145]
It would be great, if players were able to use redstone mechanics like levers, buttons, pressure plates without giving them plots.admin.interact.other permission, which allows to open containers.

**Comment by EvilOlaf** [comment]
Use the flags system und set the use flag properly.

**Comment by ziutekkk** [comment]
Doesn't work - still requires plots.admin.interact.other
I used /p flag set use 69    and levers dont work

**Comment by boy0001** [comment]
Oh, I know the issue, it requires the data to also be the same, so when you added 69, it added 69:0, but the lever is probably something like 69:3. I'll have it fixed in the next update so if you just add 69, it will include any data, or you can add 69:0 and it will just allow that.
