### ISSUE TITLE
Crashes server on /plot claim

### ISSUE THREAD

**Issue by baileyfreestone** [IntellectualCrafters/PlotSquared#146]
Ok so i have my permissions setup but when people do /plot claim it crashes server
Perms: http://pastebin.com/fFvn9KKd

**Comment by boy0001** [comment]
Can you post the crash report please?

**Comment by baileyfreestone** [comment]
http://pastebin.com/mT0DCUxC crash log

**Comment by boy0001** [comment]
You set max_plots to a too large of a number in your config, please lower it to something reasonable.

**Comment by baileyfreestone** [comment]
Whats the limit and other then that thankyou very much! appreciate it.

**Comment by boy0001** [comment]
max_plots is per player, I should really document that, so you really don't need a massive number.

**Comment by baileyfreestone** [comment]
Oh thanks we thought it was the total plots allowed, anyway apreciate very much!
