### ISSUE TITLE
Cauldron /plot auto and /plot claim

### ISSUE THREAD

**Issue by iKays** [IntellectualCrafters/PlotSquared#148]
http://pastebin.com/ueLxjEuZ

**Comment by EvilOlaf** [comment]
Either use markdown (https://guides.github.com/features/mastering-markdown/) or pastebin.com and put the link here but don't just paste your logs without formatting. No one wants to read this unformatted waste.

**Comment by boy0001** [comment]
Did you reload your server? If not, please send a copy of your startup log.

**Comment by boy0001** [comment]
Potentially fixed with the latest version. 

We haven't been given much information, as you have not provided a startup log nor answered the question. If the problem persists, you will need to provide this information.
