### ISSUE TITLE
Cant spawn mobs

### ISSUE THREAD

**Issue by ziutekkk** [IntellectualCrafters/PlotSquared#150]
Hi
On newest PlotSquared versions (2.7) I cant spawn mobs on my plots world and others via mobspawn eggs and commands (e.x Essentials). I have all enabled in config:  
 spawn:
        egg: true
        breeding: true
        custom: true
I have just checked and on PlotSquared 2.6.4 everything works ok. It must be something bugged from newest versions. Im not sure which.
Sorry for my english. Thanks

**Comment by boy0001** [comment]
Try setting

egg: false
breeding: false
custom: false

**Comment by ziutekkk** [comment]
Still happens for horses, cows, creepers, spiders, wolves.
I have no idea why only for those.

**Comment by boy0001** [comment]
Resolved as of: c408a8273084b7a578a0946d49c7202451b0fe54
