### ISSUE TITLE
Translation files 

### ISSUE THREAD

**Issue by EvilOlaf** [IntellectualCrafters/PlotSquared#155]
Enhancement. 

Ship pre-translated lang files with PlotSquared in some common languages like French, Italian, Spanish, German etc...

**Comment by boy0001** [comment]
Who would translate the files?

**Comment by EvilOlaf** [comment]
You



(At this point you need to watch my avatar in order to get it)




Just kidding.
Ask your community to contribute translations.
Maybe I'll do the upgrade to 2.7.x branch next weekend and see what I can translate to German.

**Comment by jyhsu2000** [comment]
I can help translate into `Traditional Chinese (zh-tw)` and `Simplified Chinese (zh-cn)` if there are complete language files in English.

**Comment by boy0001** [comment]
Maybe wait until next update, as we are redoing the color scheme of the plugin.

**Comment by boy0001** [comment]
Oh, I forgot about this. Some translation files will be bundled with 2.10

**Comment by kugick** [comment]
I could traduct the plugin in French. If you are interested just say..

**Comment by D3athw0rld** [comment]
Yo @kugick,j'veux bien la traduction stp :)
Sorry for the up :/

**Comment by joex92** [comment]
where can I download the translated files?
