### ISSUE TITLE
Help PlotMe -> PlotSquared

### ISSUE THREAD

**Issue by ichUndSo2014** [IntellectualCrafters/PlotSquared#156]
I would like to change from PlotMe to PlotSquared but the Konvert process does not work. First attempt ( with Plotme - core.jar and Plotme - generator.jar and plotsquared.jar ) : http://pastebin.com/iMc0f9BC
I waited 15 minutes but the konvert process does not end
Second attempt ( plotme jars deleted) : http://pastebin.com/Jw4TgDTY

**Comment by boy0001** [comment]
*I replied to your post on spigot.

**Comment by boy0001** [comment]
Please reopen if not resolved
