### ISSUE TITLE
PlotMe v0.13b Convenrt To PlotSquared 2.7.4 Error

### ISSUE THREAD

**Issue by NiceFinal** [IntellectualCrafters/PlotSquared#157]
Error Log
http://pastebin.com/i27RhYkj

Spigot Version
git-Spigot-1.7.9-R0.2-208-ge0f2e95 (MC: 1.7.10)

I can't properly to convert plotme database to plotsquared

If i upgrade plotme to 0.16.3 , player data will be remove 
Any method can solve this ?

**Comment by boy0001** [comment]
Resolved
