### ISSUE TITLE
Regenallroads causing lag spikes

### ISSUE THREAD

**Issue by recon88** [IntellectualCrafters/PlotSquared#162]
I just did a regenallroads on a world that's a bit bigger already.
It didn't last long and after 14 cycles (120 overall) it crashed with an out of memory error.
Even allocating more (4GB) didn't help at all.
Would it be possible for you to fix that? I know it's doable since other plugins have suchs mechanisms to  prevent out of memory errors. Like plugins that pregenerate land.

**Comment by boy0001** [comment]
Thanks for pointing this out. It will now unload the chunk from memory immediately after the road on that chunk is updated: 2341b2b9720f65100f8dff3e2a55a69132c46b61

**Comment by recon88** [comment]
The memory leak seems to be gone now but it's still hitting the CPU hard.
Trying to regen around ~140 regions. TPS are at 8 after 40 regions and keep going down. I can't even execute console commands properly. 
Don't know if there's a way to make it less ressource intensive but it would be nice if players can play while regen is running.

**Comment by recon88** [comment]
I was wrong. Still getting out of memory after some time. Did a good 100 regions before it happened.

**Comment by boy0001** [comment]
Try this:
http://128.199.174.66/plotsquared/PlotSquared.jar

**Comment by recon88** [comment]
It runs fast for the first ~10 regions then starts taking ages for one cycle.
Hitting the CPU even harder and TPS are at 14 ater 20 cycles.

**Comment by boy0001** [comment]
Does it still crash though?

**Comment by recon88** [comment]
It took like a 40-60 seconds for one cycle. Didn't have the time for ~200 cycles.

**Comment by boy0001** [comment]
So... it needs to be faster, but not as intensive, and not crash when updating a potential of 204,800 chunks...

**Comment by recon88** [comment]
I honestly don't care about speed. For example, Dynmap takes ~4 hours to fullrender my creative world but my TPS stay at stable 19-20.
I just need it to be stable and less intensives so players still can play.

**Comment by boy0001** [comment]
k, I think I might have a potential fix finally. I'm not sure if it's considered lag free, but it's definitely a lot better.

**Comment by boy0001** [comment]
Tomorrow I'll try to do it chunk by chunk rather than in bulk that way you won't get the lag spikes. Anyway, here is the current download: http://128.199.174.66/plotsquared/PlotSquared.jar

**Comment by recon88** [comment]
I just tried your latest version and it finally didn't crash. Was able to finish a regen with 300 regions but players still had huge lag spikes.

**Comment by dextonanderson** [comment]
Just tried to regen all my roads. I am doing about 700 regions and I seem to run out of memory after about 200 regions every time I try.

**Comment by boy0001** [comment]
Would this be on the latest version?

**Comment by dextonanderson** [comment]
Yes I have tried this on the latest version.

**Comment by boy0001** [comment]
Just made some changes. It is a lot faster, and will reschedule itself if the TPS gets too low. By "too low" it needs significant lag to reschedule, as it's still really greedy. If you want to reduce the number of chunks it needs to check, try running the trim command beforehand. 

I am testing it right now with 753,664 chunks, currently have 515,072 chunks left. If it doesn't work out (yet again), I'll reopen this issue. Otherwise I'll upload this to spigot and you can try it out.
