### ISSUE TITLE
New UUID mode + conversion

### ISSUE THREAD

**Issue by boy0001** [IntellectualCrafters/PlotSquared#165]
- Allow conversion between UUID modes
 - Add new UUID option for offline mode to be non case sensitive with usernames.
 - Automated detection of UUID mode changing for conversion (will fix several issues with playernames not being resolved)

**Comment by boy0001** [comment]
Update:
 - Added new case insensitive UUID option for Offline mode servers.
See: f3af61fe3c69917353b7af938d70ad804da82900

**Comment by boy0001** [comment]
Added. Need to test
@xion87

**Comment by xion87** [comment]
great, you got got a build to test?

**Comment by boy0001** [comment]
It doesn't work like that. There is a command for conversion:
`/plot uuidconvert <mode>`

I should test it myself though, then when it appears to be working, I'll have you try it on your server.

**Comment by xion87** [comment]
you dont tell me what i have to type... xD

**Comment by boy0001** [comment]
I did some testing and it's working so far. I still need to have settings save correctly. Plot helpers, trusted, denied should work however.
![Image](http://i.imgur.com/DIqnDp1.png)
