### ISSUE TITLE
Animal pairing does not work if natural mob spawning is disabled

### ISSUE THREAD

**Issue by EvilOlaf** [IntellectualCrafters/PlotSquared#168]
Just found this comment on SpigotMC forums:

"plot linking work but need a rejoint to the server. pairing from mobs dont work no child mob spawn"

Relating https://github.com/IntellectualCrafters/PlotSquared/commit/c408a8273084b7a578a0946d49c7202451b0fe54

Did not test/verified.

**Comment by boy0001** [comment]
Breeding works in the dev builds, so I assume it is fixed.
