### ISSUE TITLE
Sometimes a player gets randomly ported from street into a plot

### ISSUE THREAD

**Issue by EvilOlaf** [IntellectualCrafters/PlotSquared#169]
Another thing that sounds pretty weird for me.

I got several reports from players that they were sometimes when hanging around in the plot world, walking on the street, they randomly get ported by no reason inside of a plot to a random location.

There seems to be no logic behind, there are no uncommon or no flags at all on these plots, neither the players nor the console generates a message. It just happens.

We could not find any similarities between these teleports yet.

PS 2.7.4 @ Spigot 1.8

**Comment by boy0001** [comment]
Possibility: The player was standing next to a plot being cleared. (Plot expiry?)

**Comment by EvilOlaf** [comment]
Hm then the player might have be ported in the very center of the plot as it happens for the player that executed the clear command but that was or is not the case. The position seems to be random.

In the last case a player reported there were no clearing within cooee and the target plot was not empty.

Plot expiry is not enabled, auto clear on ban neither.

**Comment by boy0001** [comment]
Any more incidents?

**Comment by EvilOlaf** [comment]
No reports at all. Either fixed or cannot reproduce.
