### ISSUE TITLE
set biome packet (client side)

### ISSUE THREAD

**Issue by boy0001** [IntellectualCrafters/PlotSquared#170]
In PlotMe, when you change the biome, the plot grass is instantly updated. With PlotSquared, it doesn't seem to take effect unless you log out and back in. Is there any way to change this behavior so it is instant?

 -cowgod

**Comment by EvilOlaf** [comment]
It does, but not sometimes not correctly. See https://github.com/WorldCretornica/PlotMe-Core/issues/41

**Comment by MattBDev** [comment]
I can confirm that PlotMe can't get this to work 100% of the time. If it does, it causes memory leaks and entities to disappear. md_5 confirmed this for me when I inquired about it. It may be possible to manually send the packet to the client but I am not sure if this would still cause the bugs mentioned before.

**Comment by MattBDev** [comment]
ThinkofDeath told me that updating the biome causes a clientside memory leak because it does something funky and forgets things.

**Comment by boy0001** [comment]
Sending the chunk packet does work in updating the biome although the memory leak is still present:
http://i.imgur.com/MHjm0IN.png

It did take quite a bit of biome changes to actually run out of memory (40, although this would ultimately depend on the size of the plot). This is entirely feasible since the leak is still present if you leave and join another server. Restarting the game is required to clear it from memory.
