### ISSUE TITLE
titles flag broken

### ISSUE THREAD

**Issue by EvilOlaf** [IntellectualCrafters/PlotSquared#173]
From the SpigotMC forums:

```
/plot set flag titles false 
doesn't seem to work. I still get the title on my screen although the chat says that the flag has been successfully added :/

Please help!
```

Did not test/verify.

**Comment by boy0001** [comment]
Not really a bug, but I can change the behavior to something more desirable. Currently you will need to set titles to false, then selectively set titles to true in plots, or use the default flag system to control titles.
