### ISSUE TITLE
Cannot Set Plot Size Higher Than 32.

### ISSUE THREAD

**Issue by Frawsty0** [IntellectualCrafters/PlotSquared#178]
I cannot setup a world with plots, that are larger than 32 blocks.

Otherwise this is what happens when someone claims one: ![Image of Yaktocat](http://files.enjin.com/953205/2015-03-08_11.07.16.png)

**Comment by boy0001** [comment]
Can you post a copy of your configuration please?

**Comment by Frawsty0** [comment]
http://pastebin.com/7w3bMxka

**Comment by boy0001** [comment]
The YML file is invalid and being reset. Please user an online YML parser (http://yaml-online-parser.appspot.com/) to check your configuration after editing.

**Comment by boy0001** [comment]
By the way, if your plotworld is called "creator" then the settings for creator need to be changed rather than "plotworld". Unless of course you have multiple plot worlds.
