### ISSUE TITLE
PlotMe Conversion Error

### ISSUE THREAD

**Issue by CKGAR** [IntellectualCrafters/PlotSquared#181]
http://pastebin.com/79iCX9aK

**Comment by boy0001** [comment]
Could you provide some information:
 - Version of PlotMe
 - Version of PlotSquared
 - online or offline mode
 - Did you delete the PlotMe jar first?
 - Did UUID caching occur during startup (if unsure post full startup log).

If you are unable to provide some information, that's fine. It would just make it easier to investigate.

**Comment by boy0001** [comment]
Yeah, there's not enough info for me to verify this. If it's still a problem, please comment here.
