### ISSUE TITLE
Flag for chest access not working

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualCrafters/PlotSquared#185]
On a plot with these flags: http://gyazo.com/fada7661e5060d47ada370ba1751ff09

Other players (those not added to the plot) cannot open the chests

**Comment by EvilOlaf** [comment]
Maybe I'm wrong but wasn't the flag called `chest-access`
Also did you try to set the `use` flag to grant access to chests (ID 54)?

**Comment by boy0001** [comment]
The flag was removed 9 versions ago. See here for the current flags: https://github.com/IntellectualCrafters/PlotSquared/wiki/Usage:-Plot-flags

**Comment by PhanaticD** [comment]
I should not be able to set it then though shouldnt it say flag doesnt exist?

**Comment by PhanaticD** [comment]
its still listed: http://gyazo.com/15c1caf0e47399b934e9d55d601e135e
