### ISSUE TITLE
/Plot Home Takes me to an alternate plot world (when 2 or more plot worlds on server)

### ISSUE THREAD

**Issue by sycoinc** [IntellectualCrafters/PlotSquared#187]
doing /plot home takes me and players to their main plot on the 1st plot world created, how can this be limited to only take them to their home plot inside the world they are in

eg /plot home:1 , /plot home:2 would take them to plots in the current world not in other worlds.

Or does this have to be set to an alias

**Comment by EvilOlaf** [comment]
Hm
Sounds like this could be solved by adding an optional parameter to the `plots home` command like
`plots home [alias] [world]`

**Comment by boy0001** [comment]
I'll have the plots sorted beforehand in the next version.

**Comment by boy0001** [comment]
Added: 0c3b084f73433b62538df27f2ebb97999dd99d19
