### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by SDTCARLOS** [IntellectualCrafters/PlotSquared#190]
Hi,

We found some problems with version 2.8.7

When you clear or delete a plot the chat say "Done took %time%" not the real time in ms

Commands plot swap doesnt work, And plot move doest not exist,

Thank you!
You are the best empire!

**Comment by boy0001** [comment]
You will need to either reset the translations file or set %time% to %s
As for swap and move, do any messages display in game or in console when using the commands?
