### ISSUE TITLE
Plot owner name changes to UUID

### ISSUE THREAD

**Issue by dextonanderson** [IntellectualCrafters/PlotSquared#192]
![ss 2015-03-11 at 08 57 52](https://cloud.githubusercontent.com/assets/9245112/6610714/94bbc656-c820-11e4-87b0-3a31897e69c0.jpg)

You are unable to use any plot commands corresponding to your plot. 
ie /plot home does not work

Plotsquared 2.8.7
Spigot 1.8

**Comment by boy0001** [comment]
If you are offline mode or using pre-1.7.6 craftbukkit, please make sure that the uuid mode is set to offline in the settings.yml

If you recently updated from pre-1.7.6 builds of craftbukkit, UUID conversion from offline->online mode has not been added yet, and you should consider setting the uuid (in settings.yml) to offline until this functionality is added.

**Comment by dextonanderson** [comment]
I am using 1.8 spigot and converted from the most recent build of plotme about two weeks ago. I also have UUID mode set to offline since I am using a bungee proxy .

**Comment by boy0001** [comment]
How many plots would you guess are effected?

**Comment by dextonanderson** [comment]
So far, all plots that I have found are affected.

**Comment by boy0001** [comment]
That UUID corresponds to DBZboi1999 according to the Mojang servers meaning that it is stored in `online mode`. Could you possibly try this file, with UUID mode set to online in the PlotSquared settings.yml?

http://128.199.174.66/plotsquared/PlotSquared.jar

**Comment by dextonanderson** [comment]
I used that jar and my UUID settings are:
UUID:
  offline: false

It seems to work now. Although I had offline mode to false before. I never had changed it.
