### ISSUE TITLE
Methods of annoying players on plots which should be blocked

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualCrafters/PlotSquared#194]
TODO: testing

### NOW ADDED:
fishing rod
shooting bow and arrow
throwing XP potion
throwing regular potion
throwing snowball
throwing eye of ender (survival mode)
throwing enderpearl (survival mode)

**Comment by dextonanderson** [comment]
Maybe add these as an optional flag for arrows and throwable entities.

**Comment by boy0001** [comment]
Finished adding as of: 4d7cc990e2ba79f5b71bbe1eaa001944ba824ce1

Please comment if:
 - something doesn't work as expected
 - you can think of a better way to do it
 - You can think of more things that may annoy other players
and I will reopen this issue.
