### ISSUE TITLE
Plot Review

### ISSUE THREAD

**Issue by AyreTV** [IntellectualCrafters/PlotSquared#195]
Would it be possible to implement some form of plot review? I run an in-game convention and used PlotMe to have people build their exhibits, however I always had issues with:

A) Having it reviewed in terms of build quality, by the event build team.
B) Having it reviewed by moderators, for if a plot didn't follow guidelines but it wasn't to do with quality.
C) Keeping track of which plots would go into the event, through an internal management review.

Im currently stuck using built exclamation marks (gold = builder, red = moderator) and then placing blocks above the plots when doing the final internal review, so a system implemented to automate this so users get notifications, can easily recognise the review and generally streamline the process would be great!

**Comment by boy0001** [comment]
There is PlotRankup, which is an automated system for plot approval. You don't necessarily have to rank someone up after approving a plot, you can just execute any command, or nothing after a plot has been approved. 

In the next few weeks I may start working on a build competition addon. So the main functionality you would be looking for:
 - Creation of a build conventions
 - Submission of plots to a convention
 - Rating process (by build team)
 - Approval process (by moderators)

Links:
 - http://www.spigotmc.org/resources/plotrankup.1571/

**Comment by AyreTV** [comment]
That does sum it up, yeah. All of the building functionality is working fine as it is for our needs, its just purely that review system for build team rating, moderator approval and then management approval.

**Comment by Dooleylabs** [comment]
Finding this issue was helpful, however the plugin, [PlotRankup](http://www.spigotmc.org/resources/plotrankup.1571/), is not updated frequently enough, and there do not seem to be many updated alternatives. Suggestions?
