### ISSUE TITLE
Not able to create worlds

### ISSUE THREAD

**Issue by Kyle1264x** [IntellectualCrafters/PlotSquared#196]
Not able to do /mv create plotsquareds normal -g PlotSquared
or do .plot setup.

Casues an error to be thrown when creating the world, resulting in it failing.

**Comment by Kyle1264x** [comment]
http://pastebin.com/J9Se1pGA

When converting

**Comment by Kyle1264x** [comment]
http://pastebin.com/CQ7hqHNJ
When creating

**Comment by boy0001** [comment]
You are using an outdated version of Spigot. Please update to the latest version which fixes this NPE.
