### ISSUE TITLE
Plot home and plot visit go to random plots

### ISSUE THREAD

**Issue by dextonanderson** [IntellectualCrafters/PlotSquared#197]
For quite a few players on my active plotsquared server, using /p home and /p v <that player> will take you to another location that is not their plot. I am using MySQL for the db. I converted from the latest version of Plotme about 2 weeks ago. 

PlotSquared 2.8.8
Spigot 1.8 latest build

ie:
The intended plot was:
![ss 2015-03-13 at 11 44 45](https://cloud.githubusercontent.com/assets/9245112/6650348/38ab4d86-c9ca-11e4-8a73-94df436f3eca.png)

The plot it will teleport you to is:
![ss 2015-03-13 at 11 42 13](https://cloud.githubusercontent.com/assets/9245112/6650349/425fb9c0-c9ca-11e4-866f-a235ce02a64b.png)

**Comment by boy0001** [comment]
I had someone report this issue the other day. I think if you update to the latest dev build it should be fixed, although you will need to reset the home location for any plot existing plot.

**Comment by dextonanderson** [comment]
Yes, that solved my problem. I changed all the entries from the plot position column in plot_settings to DEFAULT and compiled the latest build.
