### ISSUE TITLE
Piston and redstone machines.

### ISSUE THREAD

**Issue by pillsforthecough** [IntellectualCrafters/PlotSquared#198]
http://i.gyazo.com/ae30ee42e56b96fc9a2e3bdafc4088c0.gif

When i try to pull a item with a sticky piston IN a plot (on the roads works well) the event of get sticky the piston was cancelled.

It works fine for the griefers, but the piston machines doesnt works... Can you look at this?

**Comment by pillsforthecough** [comment]
Oh! Another bug! Sometimes, when i restart the server, the plot owners changes... one random player get owner of the plot for another random player... its rare... could be for import players for the plotme database?

**Comment by boy0001** [comment]
duplicate/resolved.
see: 20d64508a59cccd2fff7934e1f84e3a264e3fe7d, #207, #4

Please don't get off topic in an issue, just create a new ticket. For your second comment, see #176.
