### ISSUE TITLE
Plot home issues

### ISSUE THREAD

**Issue by dextonanderson** [IntellectualCrafters/PlotSquared#200]
Sometimes, in various locations around a plot, when you set your plot home and then teleport to it, it will teleport you to the x and z, but the y will be about 20 blocks higher for no reason.

PlotSquared 2.8.9
Spigot 1.8

**Comment by boy0001** [comment]
```Think you could add an option in the config so players spawn on the outside of their plot, rather than the middle of the inside?
Example:

spawn-middle: false```

**Comment by xion87** [comment]
+ 1 for this

**Comment by EvilOlaf** [comment]
I think it may always be more safe to let a player spawn on the street at his plot and not inside, because they could get stuck or strange stuff like that.

**Comment by boy0001** [comment]
Resolved as of: 20d64508a59cccd2fff7934e1f84e3a264e3fe7d
Please re-open if further action is required.
