### ISSUE TITLE
Road wall claimed blocks desync

### ISSUE THREAD

**Issue by kangarko** [IntellectualCrafters/PlotSquared#203]
Hello,
I am using full vanilla generator in plots, and the wall blocks around the plot are not proper type according to the config, they should be different from wall around unclamed plots (44:1).
This happens espesially after merging / unmerging. 

Also when I do /p delete they persist and are not changed back to 44:0

Spigot 1.8.3 and PlotSquared build 19

**Comment by boy0001** [comment]
Oh hey! Related issue for you:
https://github.com/IntellectualCrafters/PlotSquared/issues/201

Anyway, there's an issue with the Jenkins right now where all the newer downloads all point to build #2. Download the copy of Spigot for now.

**Comment by kangarko** [comment]
Allright, thanks :)
I have seen that issue. The problem is that an empty (null) message is printed into the server's console, which result in an error. Make sure your plugin does not print null messages. In the latest version of my plugin I ignore those messages so if the user will update it should be "fixed".

**Comment by boy0001** [comment]
Added a null check
