### ISSUE TITLE
Ah these pistons issue...

### ISSUE THREAD

**Issue by xion87** [IntellectualCrafters/PlotSquared#207]
People can push blocks out plots with pistons... using plotsquared 2.8.11 and version 1.8.3 spigot
a my friend recorded the video about it: https://www.youtube.com/watch?feature=player_embedded&v=iMKrN333DAM

**Comment by boy0001** [comment]
Fixed as of: 20d64508a59cccd2fff7934e1f84e3a264e3fe7d
