### ISSUE TITLE
Augmented Plot World Road Generation

### ISSUE THREAD

**Issue by sycoinc** [IntellectualCrafters/PlotSquared#209]
Sometimes when a plot world is generated on an Augmented world the roads do not get created properly, from testing it seems when there is water under a road (mainly a river or small bed of water) the roads break and water is shown under it (like sand falling into water when no solid block is placed under it)

This happened with default road generation using wood planks as road.

**Comment by boy0001** [comment]
Is this fixed by relogging. If so I can send a chunk update along with the roads being added to the chunks.
