### ISSUE TITLE
unable to locate the sign AND where there was no entity tile!

### ISSUE THREAD

**Issue by kleinesgumi** [IntellectualCrafters/PlotSquared#212]
sometimes when i delete a Plot comes that:
Unable to Locate a sign or http://pastebin.com/Kuqd3nK7

**Comment by boy0001** [comment]
What version of PlotSquared are you using? This issue should have been fixed...

**Comment by kleinesgumi** [comment]
PlotSquared version 2.7.0
i cannot update i have spigot 1.8

**Comment by EvilOlaf** [comment]
You can not update to the current version of PS because you are using Spigot 1.8? That makes no sense to me?

**Comment by kleinesgumi** [comment]
the new version of PlotSquared dont solve the problem and in new version are big bug ._.

**Comment by boy0001** [comment]
Could you tell me what the "big bug" is? I can't fix someone I don't know about. Also, the unable to locate sign messsage should be fixed as soon as you have loaded the chunk at least once in the new version.

**Comment by kleinesgumi** [comment]
after i have update, disappears the first block row in a large radius

**Comment by boy0001** [comment]
I don't understand. Could you please explain better or have a screenshot?

**Comment by kleinesgumi** [comment]
http://fs2.directupload.net/images/user/150320/3yvctqhg.png

**Comment by boy0001** [comment]
Are you sure that wasn't WorldEdit or something else that did that?

**Comment by kleinesgumi** [comment]
i have now update i show now for erros; new problem players spawn always on the roof /p home this is crap....

**Comment by boy0001** [comment]
The original issue has been fixed. Please create a new ticket if you have another issue to report.
