### ISSUE TITLE
Plot unlink and link roads

### ISSUE THREAD

**Issue by xion87** [IntellectualCrafters/PlotSquared#214]
when unlinking a merged plots road are not generated correct (default road blocks) and i use road schematics.

**Comment by boy0001** [comment]
When plots are merged in the augmented plotworld, flat grass is placed where the roads are, rather than terrain.

**Comment by Htgan** [comment]
Another issue concerning roads. using //regen on a merged plot will regenerate the roads.
Concerning plot merging. When a player claims a new plot next to their old one and have it auto-merge, their WorldEdit will be restricted to only their old plot, as if they don't own the new plot at all. However this isn't permanent, all they need to do is relog and they will be able to WorldEdit on the entire newly merged plot.

**Comment by boy0001** [comment]
Whoops, meant to close 215

**Comment by boy0001** [comment]
update: Using `/plot weanywhere` will refresh the WorldEdit mask for a player, or toggle it for someone with the bypass permission.

**Comment by kangarko** [comment]
Hey, @boy0001, Any eta on adding proper terrain generation at the road, please?

**Comment by boy0001** [comment]
No. Sorry :(
I'll let you know once I start working on it.

**Comment by kangarko** [comment]
Thanks, since I this is the only thing preventing me from putting it on a production server.

**Comment by FrozenDroid** [comment]
I would love to see this fixed. It's not stopping me from using the plugin in production, but it's not a nice sight.

**Comment by kangarko** [comment]
@boy0001 Did you started? Sorry for spamming you but this is the only thing preventing me from putting this plugin online, players will do complain about this.

**Comment by EvilOlaf** [comment]
I  am using it for a while now and it does not  happen that often that players unlink their plots and even IF they do another player with proper permissions can do `debugroadregen` to fix this easily.

**Comment by boy0001** [comment]
Yes, I started working on it a couple days ago.

**Comment by kangarko** [comment]
Or right thank you very much :)
