### ISSUE TITLE
Reload command issues

### ISSUE THREAD

**Issue by SidiXis** [IntellectualCrafters/PlotSquared#215]
Edit by Empire92: The following bug has been fixed by a proper restart. The reload command is still broken.

Everything seems to be working - until you reload or restart the server, that is. Older builds worked great, something happenned with one of the last updates - after reloading server, PlotSquare forgets about every plot world, every plot etc - "You're not in a plot world!" and "Found no plots with your search query" after executing /plot home after reload. Tried MySQL and SQlite, both not working. I'm literally freaking out - told my players that the server will be offline for a week, and this error appeared from nowhere. Trying to go back to previous builds doesn't work either. DDD:

**Comment by EvilOlaf** [comment]
First of all you do  not want to use `/reload`. Never. It causes more problems than it could solve. You always want to do a clean restart. Do not take the risk to mess up your server by being lazy and use `/reload`.

Hard to do further investigation. Full startup log? Configuration files of PS and MultiVerse/MultiWorld (if avaliable)?

pastebin.com

**Comment by SidiXis** [comment]
Well, I guess it's something with the latest updates - I came back to 2.7.4, which is posted on BukkitDev as stable and everything came back to normal.
I don't even know what caused this, but I'm glad everything came back to normal.
And if You still want those logs, I can send them here later.

**Comment by boy0001** [comment]
Fixed: fcbfbae02ed09d131788023205e495a2ae3d24f1
