### ISSUE TITLE
Plot setowner when not claimed bug

### ISSUE THREAD

**Issue by dextonanderson** [IntellectualCrafters/PlotSquared#216]
If you try and use /p setowner on an unclaimed plot, it will return that you are not in a plot:

![ss 2015-03-21 at 07 33 33](https://cloud.githubusercontent.com/assets/9245112/6767745/4335cff0-d001-11e4-8fc2-3711f1adff31.png)

**Comment by EvilOlaf** [comment]
Duplicate https://github.com/IntellectualCrafters/PlotSquared/issues/166
