### ISSUE TITLE
Not all of the plot switches biome when using /p set biome

### ISSUE THREAD

**Issue by dextonanderson** [IntellectualCrafters/PlotSquared#217]
I've tested this on multiple plots and it always turns out like this (after relogging):

![ss 2015-03-21 at 11 32 01](https://cloud.githubusercontent.com/assets/9245112/6768044/e03b44dc-d011-11e4-9fe3-81991a45a360.jpg)

![ss 2015-03-21 at 11 33 44](https://cloud.githubusercontent.com/assets/9245112/6768049/fb32b9dc-d011-11e4-8682-79626386f3b9.jpg)

Spigot 1.8
PlotSquared 2.8.12

**Comment by EvilOlaf** [comment]
Unfortunately this issue can not be fixed by PS, because it is Minecraft related. Did you try to relog? Usually then the biome should fit fine.

**Comment by dextonanderson** [comment]
Yes I did relog. Didn't realize this was a minecraft issue. Thanks.

**Comment by EvilOlaf** [comment]
So relog fixed the issue for you?

**Comment by boy0001** [comment]
Sorry, I don't know if it's possible to fix.
