### ISSUE TITLE
Item frame protection

### ISSUE THREAD

**Issue by boy0001** [IntellectualCrafters/PlotSquared#220]

**Comment by boy0001** [comment]
cannot replicate

**Comment by Gotak99** [comment]
Why cannot replicate? Please I need to protect itemframes.

**Comment by EvilOlaf** [comment]
Describe exactly in which way your item frames are affected. Also a list of your plugins might be useful because obviously it works with PlotSquared.

**Comment by Gotak** [comment]
Players can steal items from item frame in plots with snowballs, fishing rod, enderpearl and eggs

**Comment by Gotak99** [comment]
Players can steal items from item frame in plots with snowballs, fishing rod, enderpearl and eggs

**Comment by boy0001** [comment]
Thanks for the additional information. Previously I was testing with fists and arrows.
