### ISSUE TITLE
Issue with creating road schematics

### ISSUE THREAD

**Issue by dextonanderson** [IntellectualCrafters/PlotSquared#228]
I am trying to create a new road schematic with /p createroadschematic and whenever I do so I get this in the console:
![screenshot from 2015-03-27 23 50 22](https://cloud.githubusercontent.com/assets/9245112/6879833/15a7deea-d4dc-11e4-8811-6251f78e1cf3.png)
No schematics are created and I always end up with the default roads when testing with /p debugroadregen
![screenshot from 2015-03-27 23 51 35](https://cloud.githubusercontent.com/assets/9245112/6879835/4092a39c-d4dc-11e4-8e87-1984a0eaa318.png)

Latest build of 2.8.12 plotsquared
Spigot 1.8 latest build

**Comment by boy0001** [comment]
Have you explored the entire plot? i.e. the chunks are loaded.

**Comment by dextonanderson** [comment]
Yes I have

**Comment by dextonanderson** [comment]
This seems to have been fixed in the latest version?

**Comment by boy0001** [comment]
I haven't been able to reproduce the error.

**Comment by dextonanderson** [comment]
Very strange.

**Comment by boy0001** [comment]
Is this still an issue?

**Comment by boy0001** [comment]
I'm closing this. Leave a comment, or create a new ticket if this is still a problem.
