### ISSUE TITLE
chunk issue

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualCrafters/PlotSquared#232]
a player cannot log in: http://pastebin.com/vhLG3Cce

I am also seeing this in the log, not sure if related: http://pastebin.com/fxFbtVsv

**Comment by PhanaticD** [comment]
I am using build 72

**Comment by PhanaticD** [comment]
Here is the full stack trace http://pastebin.com/BFH2Ve86

also im using build 72

**Comment by boy0001** [comment]
Apparently fixed
