### ISSUE TITLE
Much Erros in the dev build

### ISSUE THREAD

**Issue by kleinesgumi** [IntellectualCrafters/PlotSquared#234]
Console errors:
1. http://pastebin.com/4DwntVc0
2. http://pastebin.com/013V0XcE
3. http://pastebin.com/yrzsu1QK

**Comment by boy0001** [comment]
They a re all the same bug. Please use the newer version: 3477132cf22c9be39decf59b9fe572b4a6825635

**Comment by kleinesgumi** [comment]
you have say it:

boy0001 commented 10 hours ago
Try: http://ci.nixium.com/job/PlotSquared/

**Comment by kleinesgumi** [comment]
bug is fixed in the newst version... Thanks!
