### ISSUE TITLE
Chunk Artifacts on Clearing/Merging/Regenerating

### ISSUE THREAD

**Issue by ravand1990** [IntellectualCrafters/PlotSquared#236]
I noticed with the latest stable release that the memory exceptions and lag spikes are no longer occuring, however i noticed that instead of that chunk artifacts get created.

It happens when someone clears a plot, regens a road or merges a plot. Most of the time a relog fixes this issue but sometimes things stay wrong. Also the biomes don't seem to reset themselves according to the plot size either

Here are some screenshots of what happens/how it looks like:

Plot Clearing without relog:  http://puu.sh/gXsJZ/c45339b084.png
Plot Clearing after relog: http://puu.sh/gXsL3/9fe7bfe18d.png (Notice the biome indifference)

Plot Merging without relog: http://puu.sh/gXsMi/fe1439afe7.png
Plot Merging after relog: http://puu.sh/gXsNK/692335fa09.png (notice how the roads are not correct)

**Comment by boy0001** [comment]
Isolated issue with 1.7.10

**Comment by boy0001** [comment]
Resolved with latest build.
