### ISSUE TITLE
AdvPlot Worldgeneration is not working anymore?

### ISSUE THREAD

**Issue by manuk0202** [IntellectualCrafters/PlotSquared#237]
Hey there, I just updated from Version 2.6.4 to 2.9.1 and my plot's weren't working anymored so i decided to create a new plotworld. I tried Creating a world with the Generator AdvPlots with Schematics. but if i try to use AdvPlots it says: What Generator do you want? and only PlotSquared Generator is available. My plots have a tree in the Center and bridges on the borders (see Image). So if i use the Schematic on Claim Option the Players will be able to destroy the bridges too. The paths are made out of Wood and glowstone not only one block typ so is tere any option to use AdvPlots schematics with PlotSquared? 
![bild 2](https://cloud.githubusercontent.com/assets/10981356/6942928/172c21ba-d88b-11e4-9f65-59ed4a8eaede.png)
![bild 5](https://cloud.githubusercontent.com/assets/10981356/6942929/172ca446-d88b-11e4-9e55-751a7add91c5.png)
thx for your help still awesome plugin :D

**Comment by boy0001** [comment]
Hmm, looks like a bug. Could you send me your schematics? I'll see if I can get a template working for you. With the template you will be able to create the world in one step.

**Comment by manuk0202** [comment]
https://mega.co.nz/#!BhZxiCSa!exZlJPZ2745hqDeDGhkf3fJk325StQcBb1upkWuYGXE

**Comment by boy0001** [comment]
Here's your template:
https://www.dropbox.com/s/28fb1em6q5ip1mp/advworld.template?dl=0
/plot template import <world name> <template>
(The templates go in `plugins/PlotSquared/templates`)

There's also a new version of AdvPlots and PlotSquared out that should fix the setup command.

**Comment by boy0001** [comment]
Another option would be to switch to the bundled plot generator, which also supports schematics.If you want I can create another template for this.

**Comment by manuk0202** [comment]
Hey thanks for your help but it's not working for me :/ if i try generating a new world it Ends up with an error or generates just a normal flatworld. im using Version 2.9.5 now... so i have to try the other Option you told me. the Thing with the bundled plot Generator. can you tell me more about that?
