### ISSUE TITLE
Road schematic broken

### ISSUE THREAD

**Issue by kangarko** [IntellectualCrafters/PlotSquared#241]
I have set up a road schematic but objects like stars have incorrect orientation, they have no rotation at all. WorldEdit support placing with rotation so I guess you only have to call a proper methods, if you are hooking into it. Thanks.

**Comment by kangarko** [comment]
Also, when the schematic contains objects that emit light (e.g. glowstone) the light is not calculated and the chunk remains dark. Idk if this is possible to fix, but maybe calling some chunk update method after road is generated.

**Comment by boy0001** [comment]
PlotSquared doesn't depend on WorldEdit, so we can't hook into it. Is it all stairs or just upside-down ones?

**Comment by kangarko** [comment]
I dont have upside-down stairs in my schematic, just regular rotated ones, that became rotated in one rotation only.

**Comment by boy0001** [comment]
Could you send me your template then?
/plot template export <world>
"plugins/PlotSquared/templates/<world>.template"

**Comment by kangarko** [comment]
http://www.ulozto.net/xKCoh7fL/plot-template

**Comment by boy0001** [comment]
http://empcraft.com/plotsquared/PlotSquared.jar

**Comment by kangarko** [comment]
Thanks much! Good luck with your plugin.
