### ISSUE TITLE
Broken augmented generation

### ISSUE THREAD

**Issue by kangarko** [IntellectualCrafters/PlotSquared#242]
Using augmented generation in plots (ALL terrain), I have spotted this:
https://imgur.com/WlyexzK
I think this was supposed to be the double flowers, but are not generated property.
Thanks.

**Comment by boy0001** [comment]
Does relogging fix the issue?

**Comment by kangarko** [comment]
No, and they are true dead bushes since they also drop grass.

**Comment by boy0001** [comment]
If you have WorldEdit, can you try using //regen on that chunk?

**Comment by kangarko** [comment]
I've found another bugs, andesite and dirt generated inside a road (my road only contains stone,cobblestone and gravel)
https://imgur.com/U2iZTPV
btw: awesome work, the best plot plugin so far

**Comment by kangarko** [comment]
//regen by WorldEdit didn't help, it just generated things inside the road (similar to the picture above plus leaves and grass on dirt)

**Comment by boy0001** [comment]
*sigh*
Generator issues are a pain.

**Comment by kangarko** [comment]
I know, I was making a custom minecraft server last year, I dont think it is possible to achieve completelly perfect result without a complete rewrite. The things inside a road are fine, but I guess many players will complain on the grass. Maybe you can add some runnable that runs after the plot is generated and removes the dead bush? (if possible, just a workaround)

**Comment by boy0001** [comment]
Before I know why the dead brown bush is being placed there, I'd rather not add a massive workaround. Who knows, it could be something specific to that version of spigot, that's fixed in a new update. 

The things inside the road I could probably play around with the populator delay until I find something that works reasonably well.

**Comment by kangarko** [comment]
Thank you very much for the effort, amazing plugin.

**Comment by boy0001** [comment]
Okay, I'll close it, but only because I somehow figured it out!! Yay! :D

It will be fixed in the next version I upload.
