### ISSUE TITLE
Cannot load templates

### ISSUE THREAD

**Issue by kangarko** [IntellectualCrafters/PlotSquared#246]
I noticed there are two templates by default in the template folder: town and skyblock.
However, I cannot load them. Every time I end up with a message saying "Invalid template file: town.template". I have entered command:

/p template import creative town

Is this a bug or am I doing something wrong?

**Comment by kangarko** [comment]
I notices error in the console:
http://pastebin.com/3TYK5UUu

**Comment by boy0001** [comment]
I took a look at the templates and it turns out they are corrupt. I even tried older versions of PlotSquared that I upload but had the same result.

**Comment by boy0001** [comment]
Fixed. It was an issue with the pom settings which lead to maven corrupting the templates
