### ISSUE TITLE
Plot floor/walls

### ISSUE THREAD

**Issue by AnnioOoO** [IntellectualCrafters/PlotSquared#247]
Setting plot floors and walls will only generate for one plot, despite plots being merged.
![2015-04-03_18 47 14](https://cloud.githubusercontent.com/assets/11268471/6985270/e32db754-da31-11e4-9838-76865dc65f9c.png)

What I did: 
Claimed 2 plots. Set the wall (birch-logs), which worked for the whole merged plot but it was set one block too low. So I set the wall-height in the config one block higher. 
Restarted the server. No errors. Tried to set the wall again and it only created the walls for one plot and not the whole merged one - same with the floor.
I tried to merge, and unlink this plot but it didnt work. If I try to unlink, it tells me that only mega plots can be unlinked. If I try to merge manually (it's set to automerge) it tells me that I dont own the next plot (which is correct if you assume that this plot is still merged).

**Comment by boy0001** [comment]
Cannot replicate. Is it still an issue with the latest version?

**Comment by AnnioOoO** [comment]
It seems to work just fine after the last update!
