### ISSUE TITLE
Plot flag info inaccurate

### ISSUE THREAD

**Issue by Theepwner** [IntellectualCrafters/PlotSquared#248]
I have set a certain plot's flag with "/p flag set titles false", but when checking the flag with "/p flag info titles" it will show it as "Not implemented".

The flag is working as expected, just "/p flag info titles" won't show if it's at true/false. I suspect this is the same for every flag available.

**Comment by boy0001** [comment]
Can you show a screenshot please?

**Comment by Theepwner** [comment]
Here: http://i.imgur.com/ACpKvke.jpg

**Comment by Theepwner** [comment]
Hmm, just realized /p info shows the current flags and flag values you have set. But what exactly does the "Not implemented" in "/p flag info <flag>" stand for?

**Comment by boy0001** [comment]
It's the in game documentation that's "not implemented". In the future it will display information about what the flag does etc.
