### ISSUE TITLE
Can't import PlotSquared world after updating to 2.9.4/5

### ISSUE THREAD

**Issue by Ashbrooke** [IntellectualCrafters/PlotSquared#253]
Fails to load the PlotSquared world on startup and can't be imported in afterwards. Ran chunkster with no effect. If I disable PlotSquared the world loads into multiverse without any issues. I also can't generate a new PlotSquared world. Deleted all of the configuration files and regenerated them, also didn't help. Then I tried rolling back to an older PlotSquared version, but couldn't get it to work again.

Really love the plugin and would like to get it working again :(
Thanks for any help.

Running Spigot 1.8.3

Console:
04.04 16:47:28 [Server] ERROR Failed to Create/Load the world 'crafterville'
04.04 16:47:28 [Server] ERROR http://forums.bukkit.org/threads/admin-chunkster.8186/
04.04 16:47:28 [Server] ERROR Try using Chukster to repair your world! 'crafterville'
04.04 16:47:28 [Server] ERROR The world 'crafterville' could NOT be loaded because it contains errors!
04.04 16:47:28 [Server] WARN at java.lang.Thread.run(Thread.java:745)
04.04 16:47:28 [Server] WARN at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
04.04 16:47:28 [Server] WARN at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
04.04 16:47:28 [Server] WARN at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
04.04 16:47:28 [Server] WARN at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710)
04.04 16:47:28 [Server] WARN at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60)
04.04 16:47:28 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:262)
04.04 16:47:28 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
04.04 16:47:28 [Server] WARN at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13)
04.04 16:47:28 [Server] WARN at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
04.04 16:47:28 [Server] WARN at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
04.04 16:47:28 [Server] WARN at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968)
04.04 16:47:28 [Server] WARN at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133)
04.04 16:47:28 [Server] WARN at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646)
04.04 16:47:28 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
04.04 16:47:28 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
04.04 16:47:28 [Server] WARN at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:897)
04.04 16:47:28 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
04.04 16:47:28 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
04.04 16:47:28 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
04.04 16:47:28 [Server] WARN at com.onarandombox.MultiverseCore.commands.ImportCommand.runCommand(ImportCommand.java:147)
04.04 16:47:28 [Server] WARN at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:229)
04.04 16:47:28 [Server] WARN at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:421)
04.04 16:47:28 [Server] WARN at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261)
04.04 16:47:28 [Server] WARN at org.bukkit.Bukkit.createWorld(Bukkit.java:463)
04.04 16:47:28 [Server] WARN at org.bukkit.craftbukkit.v1_8_R2.CraftServer.createWorld(CraftServer.java:893)
04.04 16:47:28 [Server] WARN at net.minecraft.server.v1_8_R2.WorldServer.<init>(WorldServer.java:57)
04.04 16:47:28 [Server] WARN at net.minecraft.server.v1_8_R2.World.<init>(World.java:180)
04.04 16:47:28 [Server] WARN at com.intellectualcrafters.plot.object.PlotGenerator.getDefaultPopulators(PlotGenerator.java:46)
04.04 16:47:28 [Server] WARN at org.bukkit.craftbukkit.v1_8_R2.CraftWorld.getName(CraftWorld.java:489)
04.04 16:47:28 [Server] WARN java.lang.NullPointerException

**Comment by 7rory768** [comment]
I, too am having this issue, worked before after updating to 1.8.3 it no longer works.

**Comment by boy0001** [comment]
Update to the latest version of Spigot. It should fix the issue. Use buildtools or getspigot.org
