### ISSUE TITLE
Feature: Command to toggle plot titles

### ISSUE THREAD

**Issue by Theepwner** [IntellectualCrafters/PlotSquared#254]
I think it would be a cool feature for players to be able to toggle whether or not they want to see plot titles.

Ex: /plot titles [on/off]

I realize as of now you can only disable or enable this in the settings.yml, or set the plot flag to title false, but most players would like the option to choose.

Thanks.

**Comment by Theepwner** [comment]
This isn't that necessary if #206 if implemented. Your choice though.

**Comment by boy0001** [comment]
I don't want to have to store per player preferences. #206 is a much easier solution.

**Comment by boy0001** [comment]
Added as of: 93a40653c0d8def43290d6c23bbbd32a5db3e618

`/plot toggle titles`
