### ISSUE TITLE
Road schematics not in effect for road after /p unlink

### ISSUE THREAD

**Issue by Theepwner** [IntellectualCrafters/PlotSquared#258]
After setting up road schematics, if a player merges plots, then later does /p unlink, the roads will be set to default wool. Not sure why regular wool, since I do not have that anywhere in the settings.yml for this world. The issue is the road schematic isn't loaded.

After unlinking: http://i.imgur.com/vRYzTs6.jpg

Additionally, to get the road schematic back I have tried /p delete on both plots, yet there seems to be section(s) of the road missing.
http://i.imgur.com/jwLQjIf.jpg
Note: Not visual glitch

**Comment by EvilOlaf** [comment]
Propably known issue. Duplicate

**Comment by Theepwner** [comment]
My bad, see it at #214
