### ISSUE TITLE
Plot world

### ISSUE THREAD

**Issue by Koalaman1** [IntellectualCrafters/PlotSquared#263]
I restart the server go though the portal to the Plotworld and it doesnt know that is a plot world

**Comment by EvilOlaf** [comment]
Great for you. No one has a second sight, so provide some information like startup logs, plugin versions, plugins configuration files, Bukkit version....
Use pastebin.com for that.

**Comment by boy0001** [comment]
Possible solutions
 - If you used the `/reload` command, the solution is to not use it as it will not reload the worlds.
 - Make sure the generator is set (post your startup log / settings.yml)
