### ISSUE TITLE
Minecarts not counting towards entity-cap/mob-cap flag

### ISSUE THREAD

**Issue by xxMOxMOxx** [IntellectualCrafters/PlotSquared#266]
Title says it all. Minecarts didn't use to count towards the entity-cap flag (now mob-cap) which means players can spawn in huge amounts of minecarts, potentially causing lag and even crashes. Minecarts counting towards this cap or having a separate flag would be greatly appreciated
Tested in version 2.9.12

**Comment by dextonanderson** [comment]
I would also like to see this feature implemented.

**Comment by boy0001** [comment]
vehicle-cap ?

Until then, you could consider trying the chunk processor, although this will only activate when the chunk is saved/loaded.
