### ISSUE TITLE
plots.worldedit.bypass broken?

### ISSUE THREAD

**Issue by EvilOlaf** [IntellectualCrafters/PlotSquared#279]
Following scenario:
I have a users with `*` permission (I know that's a terrible idea, just for testing purpose).
This user tries to use WorldEdit on a plot which does not belong to him.
`/p weanywhere` removes this restriction.

`plots.worldedit.bypass` should be included in `*` so is it broken?

Anyway this behavior is not that bad because it can be used to prevent accidently hit other players plots.

**Comment by boy0001** [comment]
Undocumented feature
