### ISSUE TITLE
Plot Biome

### ISSUE THREAD

**Issue by AnnioOoO** [IntellectualCrafters/PlotSquared#282]
The biome of a merged plot only changes partially. In this example the right corner is a different biome than the rest of the plot and it is even different to the default biome.
Even if the player is standing directly in that part of the megaplot, it will not change.

![2015-04-20_20 07 14](https://cloud.githubusercontent.com/assets/11268471/7237247/913995c8-e79a-11e4-8a9f-4b03d992879a.png)

**Comment by boy0001** [comment]
Is this using the setbiome command?

**Comment by EvilOlaf** [comment]
Did you relog to see if it changes?

**Comment by AnnioOoO** [comment]
A player tried to change this plot biome multiple times with /plot set biome and different biome types. Only this corner wont change no matter what. It persists after relogging (I see it too) and restarting the server. The only thing I haven't tried yet, is to unlink the plot.

**Comment by boy0001** [comment]
It appears to be an issue specific to that chunk. I can't replicate right now, but I'll spend some more time in a few.

If you have WorldEdit installed, could you see if it is able to set the biome correctly?

**Comment by AnnioOoO** [comment]
I'll try that in a few hours.

**Comment by AnnioOoO** [comment]
I modified the biome with worldedit. Now it works just fine and even changes to other biomes when using the plot set biome command. No idea why this occured in the first place.

**Comment by boy0001** [comment]
Possible corrupted chunk? I'll reopen if someone else has the issue.
