### ISSUE TITLE
explosions breaking sidewalk

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualCrafters/PlotSquared#286]
if your plot is a nether biome and you place a bed, the explosion will break the walkways

**Comment by EvilOlaf** [comment]
Hilarious xD

**Comment by Theepwner** [comment]
Confirmed.

**Comment by boy0001** [comment]
Since when was nether a biome?

**Comment by boy0001** [comment]
Oh, it's called "HELL" that's why I couldn't find it.

**Comment by EvilOlaf** [comment]
Exactly :D

**Comment by boy0001** [comment]
Not happening for me? 
http://i.imgur.com/9Kp6CCh.png

**Comment by EvilOlaf** [comment]
Confirmed. Spigot 1.8.3 with PS2.9.15
