### ISSUE TITLE
Changing plot biome only updates 1 section until relog

### ISSUE THREAD

**Issue by Theepwner** [IntellectualCrafters/PlotSquared#287]
Using /p set biome hell, from forest biome:
http://i.imgur.com/pY1Siip.jpg
Notice how only that corner is changed visually. Relogging will make it all how it should be.

Also, it seems like there is a grass border that looks a bit different than the other blocks.
http://imgur.com/wnL4Noa

Hope you can fix these visual "bugs", and hopefully these aren't just my issue.

**Comment by EvilOlaf** [comment]
Known issue which can probably not be fixed by PlotSquared due to limitations in Minecraft. Blame Mojang for this ^^

**Comment by Theepwner** [comment]
I'd also like to note that you can see the new biomes after simply re-loading those chunks, in addition to re-logging.

**Comment by EvilOlaf** [comment]
Also see https://github.com/IntellectualCrafters/PlotSquared/issues/217

**Comment by Theepwner** [comment]
Issue seems a bit different than that.

**Comment by boy0001** [comment]
More similar to #170 I'd say.
