### ISSUE TITLE
Flat File Support?

### ISSUE THREAD

**Issue by Emalton** [IntellectualCrafters/PlotSquared#294]
Hello there! I have looked at your plugin, and I say it looks wonderful! The sad thing is, I don't have a SQL Server / SQL Lite. Could you possibly create a method for flat file support? If there is already a method to do this, let me know!

Thanks,
Emalton

**Comment by jyhsu2000** [comment]
SQLite is a file type.
File extension is .sqlite.
No need to run a database server for it.

**Comment by boy0001** [comment]
You don't need to do anything to use SQLite, just run the server without configuring the storage.yml file.
