### ISSUE TITLE
blocks change in templates 

### ISSUE THREAD

**Issue by manuk0202** [IntellectualCrafters/PlotSquared#296]
Hey there, finally i got my stupid template working :D but i have a new Problem :/ some blocks are set in the wrong directions like stairs and half blocks. some bocks changed to the plocks without Sub-id (like 17:1 to 17) This issues were fixed when it was still possible to generate the world with advplots. when Generating a world with a template this issue still exists :/ (see Picture) you know how to fix this?
![2015-05-04_12 05 40](https://cloud.githubusercontent.com/assets/10981356/7451889/8b663a2c-f256-11e4-9058-eb180e590ac2.png)

**Comment by manuk0202** [comment]
and it should look like this (Picture made at version 1.6.2):
![2015-03-31_22 05 41](https://cloud.githubusercontent.com/assets/10981356/7451973/9bab4da4-f257-11e4-98fc-7dc2699f74af.png)

**Comment by boy0001** [comment]
It's a bug with the generator. Will be fixed soon

**Comment by boy0001** [comment]
The issue has been fixed. I will have an update on spigot in the next few hours. Remember to:
 - Update AdvPlots
 - Update PlotSquared
