### ISSUE TITLE
Players  are able to break chest in other plots

### ISSUE THREAD

**Issue by xion87** [IntellectualCrafters/PlotSquared#304]
I noticed player can break the chests in other plots by using a sword in creative mode

**Comment by boy0001** [comment]
I can't replicate this. Blocks can't even be destroyed with swords in creative.

**Comment by boy0001** [comment]
I might be using a different version, which prevents me from replicating this. It's likely to be related to fire (#301), so hopefully it's fixed.

**Comment by boy0001** [comment]
*Try the latest download from spigot.

**Comment by xion87** [comment]
i am using already the lastest version on spigot

**Comment by boy0001** [comment]
I was referring to 2.10.7 which included a fix for the fire issue. I uploaded it recently so you could test it out to see if it also fixed this issue.

**Comment by boy0001** [comment]
Can I close this?

**Comment by xion87** [comment]
I think so :D! thank you a lot

Il 15/05/2015 6.02, Jesse Boyd ha scritto:
