### ISSUE TITLE
Protect Plot???

### ISSUE THREAD

**Issue by cwhiteyuk** [IntellectualCrafters/PlotSquared#306]
How to set up protect plot on our server using PlotSquared plugin which it create plot and I been claimed one plot and other player still can build or destroyed my plot.

How stop this happing?

Thanks,

**Comment by boy0001** [comment]
PlotSquared will protect a plot normally. Make sure the other player doesn't have the permission `plots.admin`, is not op, and has not been added to your plot.

If the problem persists, please tell me what you have done to create this world and send me the following:
 - Startup log
 - settings.yml

**Comment by boy0001** [comment]
Please comment with the requested information to reopen this ticket

**Comment by techchris427** [comment]
If you have Essentials, you must disable Anti-Build in the config.
