### ISSUE TITLE
Wiki Example Configuration: global_limits and max_plots

### ISSUE THREAD

**Issue by EvilOlaf** [IntellectualCrafters/PlotSquared#308]
It seems that both `global_limits` and `max_plots` values are doing the same. However one is configuration based, the other is permission based.

If the limit node is for per world use this needs to be updated.

**Comment by boy0001** [comment]
The limit node is either global or per world depending on the value of global_limits

**Comment by EvilOlaf** [comment]
This information should be added anyways or I didn't see it.

**Comment by boy0001** [comment]
https://github.com/IntellectualCrafters/PlotSquared/wiki/Example-configuration#global_limits
https://github.com/IntellectualCrafters/PlotSquared/wiki/Example-configuration#max_plots

**Comment by boy0001** [comment]
Okay, I added that to the wiki. If you think it could be phrased better, feel free to edit the page.

**Comment by EvilOlaf** [comment]
So actually you need to add the `plots.plot.<x>` node specifically to a world by using your favorite permission management system. To say this is not handled by PS.
