### ISSUE TITLE
Can't claim more plots

### ISSUE THREAD

**Issue by cwhiteyuk** [IntellectualCrafters/PlotSquared#309]
I added plots.use and plots.claim in permission and I no longer able to claim more plots.

I get "[P2] You can't claim more plots" message when I try to claim plots but I have not claim any yet!

How to change it in permission?

Thanks

**Comment by boy0001** [comment]
Add the permission: `plots.plot.1`, to claim 1 plot

**Comment by craigbrian** [comment]
This is the most AMAZING plot plugin ever, thank you so much boy0001, Empire92 and Citymonstret
but This took me two days to find, I was having the exact same issue please put this on the front of the dev.bukkit, spigot.mc and plotsquared.empcraft important permssions
adding plots.plot.1 fixed my issue "[P2] You can't claim more plots"

**Comment by x0Z3ro0x** [comment]
I have added that permission node and I still get the message. Any idea whats going on?

**Comment by EvilOlaf** [comment]
This would allow you to claim one plot. If you want to claim more you need to raise the number of the permission node.

**Comment by thadd6408i** [comment]
use plots.plot.1 to claim 1 plot, plots.plot.2 to claim 2 plots, plots.plot.3 to claim 3 plots,... and so on
