### ISSUE TITLE
Mypet in aggressive behavior can kill mobs in plots

### ISSUE THREAD

**Issue by xion87** [IntellectualCrafters/PlotSquared#313]
I noticed that having a mypet in aggressive behavior can kill mobs into plots such horses, villagers, ecc...

**Comment by boy0001** [comment]
Can you disable aggressive behavior with that plugin?

**Comment by xion87** [comment]
yeah by using permission, i looked it now... consider it solved

Il 21/05/2015 9.10, Jesse Boyd ha scritto:
