### ISSUE TITLE
Trusted players can only build on plot is owner is online

### ISSUE THREAD

**Issue by DDevilISL** [IntellectualCrafters/PlotSquared#315]
Idk if this is a bug, or if it's meant to work like this or if I'm just an idiot and can't fix this. But the players on my server can't build on trusted plots if the owner is offline, it would be cool to add an option to disable this, awesome plugin btw :)

**Comment by boy0001** [comment]
This really depends what version you are using. With the 2.11 update, Helpers and Trusted were replaced by Members and Trusted.

Are you able to confirm the version, and whether users are added as members, trusted, helpers etc?

**Comment by DDevilISL** [comment]
I'm using 2.11.6, people have been using /plot add, i guess they should be using /plot trust right? Oh crap
Sry for wasting your time Kkkk And thanks for the plugin :)
