### ISSUE TITLE
/p deny bug

### ISSUE THREAD

**Issue by Theepwner** [IntellectualCrafters/PlotSquared#321]
Using /p deny on a player that is inside your plot will make him glitchy in his current position, not able to type any commands or move. I believe the correct behavior is to send him to the server's spawn.

Using version 2.11.8 with the latest spigot 1.8.3 build.

**Comment by PhanaticD** [comment]
was just about to report this

**Comment by Sauilitired** [comment]
Forgot to to actually player xD
