### ISSUE TITLE
PlotSquared 2.11.8 PVP flag, notify-leave and entity-item-frame-destroy not working on plots

### ISSUE THREAD

**Issue by craigbrian** [IntellectualCrafters/PlotSquared#325]
You can enable notify-leave but it wont say anything in chat and you can't type a message
PVP you can enable but it has no effect on the plots.

and could you please add entity-item-frame-destroy so mobs cant destroy item frames and paintings.

**Comment by Sauilitired** [comment]
@boy0001 still an issue?

**Comment by craigbrian** [comment]
There's still no flag for entity-item-frame-destroy and no entity-item-painting-destroy

notify-leave works but PVP allow on Bukkit, Spigot, Cauldron servers works as long as certain plugins aren't on the server they seem to interfere with PVP not working in plot worlds only.

**Comment by Sauilitired** [comment]
@craigbrian:
So, could you possibly do some private investigation and see what plugins you have that override our PVP flagging? As for the entity-item-frame flag and such, the `hanging-break` flag should cover it for players. We disabled breaking of hanging entities by entities, as we cannot find any practical use for such behaviour. 

If you manage to find any conflicting pvp plugins, then feel free to open a new ticket.
