### ISSUE TITLE
Global flags

### ISSUE THREAD

**Issue by edyyy** [IntellectualCrafters/PlotSquared#327]
My suggestion would be adding a way of adding global flags for plots. 

So if I wanted to make some blocks use-able by anyone, such as trapped chests. At the moment each and every player has to do it by himself/herself. But this can get confusing and complicated for players. 

The way global flags would work is, you set a flag with either using a command or config and that flag would take effect on all of the plots in server. Which would be extremely useful!

**Comment by EvilOlaf** [comment]
Agree.

If needed and wanted users can override those global flags  like use by setting their own.

**Comment by boy0001** [comment]
Already a feature:
https://github.com/IntellectualCrafters/PlotSquared/wiki/Usage:-Plot-flags#default-flags

**Comment by EvilOlaf** [comment]
Ya, of course. I barely remembered that there was something but wasn't sure and couldn't find quickly in documentation.
