### ISSUE TITLE
isMerged(PlotId 1, PlotId 2) API feature

### ISSUE THREAD

**Issue by diecode** [IntellectualCrafters/PlotSquared#329]
I would like check that two plots are merged or not.

for example:

```java
Plot player1plot;
Plot player2plot;

if (isMerged(player1plot.getId(), player2plot.getId()) {
// todo
}
```

**Comment by boy0001** [comment]
`MainUtil.getBottomPlot(plot1).equals(MainUtil.getBottomPlot(plot2))`

Another thing is that using the API to get the plot at a location will always return the bottom plot.

**Comment by diecode** [comment]
Thanks, this is ok for me :)
