### ISSUE TITLE
Cannot rate plots

### ISSUE THREAD

**Issue by diecode** [IntellectualCrafters/PlotSquared#331]
I tried rate my plots with other character, and I get "You have already rated plot x;y" but I didn't. When I type /p info, then the rate is 0,0/10.

![2015-05-31_23 17 56](https://cloud.githubusercontent.com/assets/3225958/7903950/be55f51c-07eb-11e5-9885-6ce8044ef6bd.png)

**Comment by boy0001** [comment]
Fixed in latest version
