### ISSUE TITLE
reload command is not loading plots

### ISSUE THREAD

**Issue by diecode** [IntellectualCrafters/PlotSquared#332]
When I use "/reload", then the plugin is not loading the plots, All plots are "not claimed".

**Comment by SirNickParks** [comment]
I do believe that /reload isn't even a supported command anymore. At least according to the in-game message. 

Screenshot:
![Screenshot](http://nkp.us/b6iyq.png)

**Comment by EvilOlaf** [comment]
That's true. You definitely don't want to `reload` your server at all. You always want to do a clean restart. `reload`breaks more stuff than it fixes.

**Comment by diecode** [comment]
Lots of people use /reload, but I know it is not recommended.

**Comment by EvilOlaf** [comment]
As long as the dont' complain someone else because the run in trouble...

**Comment by boy0001** [comment]
Fixed as of eeea1f2d2d383da623874a458df60f98fc2eddeb
Regardless, you still shouldn't be using reload.
