### ISSUE TITLE
Furniture can't be placed

### ISSUE THREAD

**Issue by SirNickParks** [IntellectualCrafters/PlotSquared#334]
I believe this is due to a flag that I can't find or that is bugged?

I turned all flags to true/enabled everything to be placed. However I can't spawn in furniture (which I believe has something to do with a flag with mobs, considering it uses Armor Stands).

If any insight could be looked into this?

http://www.spigotmc.org/resources/furniture-plugin-m%C3%B6bel-plugin.6006/

**Comment by boy0001** [comment]
This isn't an issue with PlotSquared. The author of that plugin chose to only support a select number of protection plugins rather than using the event system.
