### ISSUE TITLE
Cluster subcommand not found

### ISSUE THREAD

**Issue by ClaytonAndrews** [IntellectualCrafters/PlotSquared#339]
I have followed the steps in "Augmented Plot Worlds" and I get "That is not a valid subcommand". I changed my world name to my world's name as directed and I am using version 2.11.13.

I noticed the Cluster subcommand seems to be missing from BukkitMain.java, is that related or am I doing something wrong?

**Comment by boy0001** [comment]
enable clusters in the settings.yml

**Comment by ClaytonAndrews** [comment]
I believe I enabled it when following the guide.
It looks like this, right?
clusters:
  enabled: true

**Comment by boy0001** [comment]
Yes. You will need to do a full restart of the server for it to take effect.

**Comment by boy0001** [comment]
oh shit, you're right. I'll fix that this sec.

**Comment by ClaytonAndrews** [comment]
I have restarted the server and the subcommand is still missing. It should be a 3 step process as shown in the guide?
1) Enable clusters
2) Copy sample world config and change world name to your own
3) Reboot server

I have tried the command on an OPed player and in console.

**Comment by ClaytonAndrews** [comment]
Awesome, thank you.

**Comment by boy0001** [comment]
I have no idea how I managed to remove that command, but it's fixed now:
http://www.spigotmc.org/resources/plotsquared.1177/download?version=28700

**Comment by ClaytonAndrews** [comment]
Works now, thank you.
