### ISSUE TITLE
Trim all out of memory

### ISSUE THREAD

**Issue by confuser** [IntellectualCrafters/PlotSquared#340]
Just converted from PlotMe to PlotSquared.

Tried running `plot trim all world`

Get a lot of output in the console about removing chunks, but the server then shuts down due to an out of memory error.

The minecraft instance is assigned 15gb of memory. We probably have a lot of regions that can be trimmed. On start up with 1 player, the server only uses around 2gb, so trim must be storing a lot of information in memory to use up 13gb.

**Comment by boy0001** [comment]
Hmm, that shouldn't be happening. I'll take a look right now.
Also if you want to hop on IRC that might make it easier if I require further information.
http://webchat.esper.net/?nick=&channels=IntellectualCrafters&fg_color=000&fg_sec_color=000&bg_color=FFF

**Comment by boy0001** [comment]
If you have a copy of the console output, that may be useful.

**Comment by boy0001** [comment]
Possible fix:
http://www.spigotmc.org/resources/plotsquared.1177/download?version=28730

**Comment by confuser** [comment]
Fixed, thank you very much :+1:
