### ISSUE TITLE
Staff monitor plot chat

### ISSUE THREAD

**Issue by confuser** [IntellectualCrafters/PlotSquared#345]
Whilst our players love the `/plot chat` feature, we need the ability for staff to see plot chat for monitoring purposes. A social spy of sorts, via a permission.

From looking at the source code, it should be as simple as converting the if check into an or, by first adding a permission check.

https://github.com/IntellectualCrafters/PlotSquared/blob/master/PlotSquared/src/main/java/com/intellectualcrafters/plot/listeners/PlayerEvents.java#L413

Would you accept a PR for this? If so, what are your preferred permission naming conventions; `plots.chat.bypass`?

**Comment by boy0001** [comment]
`plots.admin.command.chat`?

**Comment by confuser** [comment]
Fixed in #350
