### ISSUE TITLE
Regenallroads bug

### ISSUE THREAD

**Issue by diecode** [IntellectualCrafters/PlotSquared#360]
The wood blocks has bad postions sometimes

(left the good, right the bad)

![2015-06-22_18 30 17](https://cloud.githubusercontent.com/assets/3225958/8286934/eca5d5ea-190c-11e5-85f2-d8e384fc850a.png)

**Comment by diecode** [comment]
When can you fix this?

**Comment by boy0001** [comment]
When I have time
