### ISSUE TITLE
/p deny exempt

### ISSUE THREAD

**Issue by confuser** [IntellectualCrafters/PlotSquared#361]
PlotMe allowed us to prevent players (staff) with a certain permission node to be exempt from being denied from plots.

Adding a permission check won't work in this case as PlotSquared allows players to be denied whilst offline. What are your thoughts on working around this? Is there an in-built way to store some sort of 'meta' data on a plot player?

**Comment by boy0001** [comment]
Add "plots.admin.entry.denied" to players and they will be able to enter plots they are denied to.

As for the PlotPlayer object, you can set non persistent meta data:
``` java
plotplayer.setMeta(String key, Object value);
plotplayer.getMeta(String key);
plotplayer.deleteMeta(String key);
```

You can also set persistent attributes (these are either set or unset and hold no value)
```
plotplayer.setAttribute(String key);
plotplayer.getAttribute(String key);
```
As of 4f7de9bf13ef0ad54a4b64397824b0e9716bd53e you can now wrap OfflinePlayer to get the PlotPlayer object (which you can then check the attributes of)

``` java
BukkitUtil.getPlayer(final OfflinePlayer op);
```

**Comment by confuser** [comment]
:+1:
