### ISSUE TITLE
Plugin apply flag setup on all plot

### ISSUE THREAD

**Issue by diecode** [IntellectualCrafters/PlotSquared#363]
When I use /plot flag set <flag> <value> command, then the plugin apply flag on my ALL plots.

Example:
I have two plot: 0;0, 0;1

I type "/plot flag set animal-attack true" on plot 0;0.
On the 0;0 and 0;1 plot has "animal-attack true" flag.

I tried with custom flag, but same.

**Comment by boy0001** [comment]
Thanks, this has been fixed for the latest download. 

It was an isolated issue with `/plot info` i.e. the flags in the `/plot list` tooltip would have been correct.
