### ISSUE TITLE
Failure in install?

### ISSUE THREAD

**Issue by M9GLiquid** [IntellectualCrafters/PlotSquared#368]
I downloaded and installed the plugin on my server; this part worked marvelous;
I tried converting it by following the instructions they have setup.
I went on and tried creating the new world (multiverse) And it gave me an error:
http://prntscr.com/7o7q6s
http://pastebin.com/zTJzcpic

I then downloaded another generator the plotsquaredSG and ran that... it created the world successfully but then no response from plotsquare plot management. I believe there to be a problem with plotsquared but I cannot find it :(

Regards,
Thomas

**Comment by Sauilitired** [comment]
Are you running the latest version of Multiverse? Could you possibly upload your plotsquared config to pastebin? 

Related stacktrace:
```java
03.07 00:00:26 [Server] WARN at com.intellectualcrafters.plot.object.PlotGenerator.generateExtBlockSections(PlotGenerator.java:87)
03.07 00:00:26 [Server] WARN at com.intellectualcrafters.plot.PlotSquared.loadWorld(PlotSquared.java:315)
03.07 00:00:26 [Server] WARN at com.intellectualcrafters.plot.generator.HybridGen.init(HybridGen.java:97)
03.07 00:00:26 [Server] WARN java.lang.NullPointerException
```

**Comment by boy0001** [comment]
That stacktrace is the result of the world being null and occurs after world creation.

@M9GLiquid 
Do you have the full stacktrace, or the server log?
Logs would normally be found in the "logs" folder for the server.

**Comment by M9GLiquid** [comment]
This is the Log File: (All related)
http://pastebin.com/QG8miYT1
This is the Settings Config of plotsquared:
http://pastebin.com/yCFxNAef

**Comment by M9GLiquid** [comment]
Also I am using this multiverse: (Altho it seems not to havebeen updated for some time now)
https://www.spigotmc.org/resources/multiverse-core.390/
multiverse-core_2.5.jar

**Comment by boy0001** [comment]
Setup MySQL properly, or use SQLite

```[23:39:00] [Server thread/INFO]: [Plots] MySQL is not setup correctly. The plugin will disable itself.
[23:39:00] [Server thread/INFO]: ==== Here is an ugly stacktrace if you are interested in those things ====```
