### ISSUE TITLE
Problem with Lockette plugins

### ISSUE THREAD

**Issue by wong318** [IntellectualCrafters/PlotSquared#369]
Can you fix this bug?
This plugins have some problem with "Lockette plugins"
When I use /plot trust to someone,he can break my leckette signs even if he without permissions.
The Lockette plugins is here:
http://dev.bukkit.org/bukkit-plugins/lockette/
Please

**Comment by Sauilitired** [comment]
@boy0001: This is weird, our listeners shouldn't override anything. However, adding a simple hook wouldn't be too hard:question:

**Comment by boy0001** [comment]
Our listeners only cancel, the don't un-cancel, ever.

**Comment by Sauilitired** [comment]
This cannot be caused by us, and should be reported to the Lockette authors.
