### ISSUE TITLE
player are able to place armorstand into any plots...

### ISSUE THREAD

**Issue by xion87** [IntellectualCrafters/PlotSquared#375]
I just noticed after the update, players are able to place armor stand in any don't owned plots..... using version 2.11.27  and 1.8.7 (creative server), don't happen in survival mode

**Comment by lucasdidur** [comment]
Bots too

**Comment by boy0001** [comment]
Duplicate issue, also has been fixed as of: 3a1577469b1647ef56b1c3a3f7b65de5e7d4994b
