### ISSUE TITLE
Chunks close to roads "is in the wrong location; relocating".

### ISSUE THREAD

**Issue by james652** [IntellectualCrafters/PlotSquared#379]
Hi,

This issue came to my attention a week ago. At the time, we dismissed it as it appeared to only be small amounts of damage.

It came to my attention again yesterday. I put PlotSquared as the most likely cause and so proceeded to update the plugin.

In the same location today, the issue reoccured with the latest version of PlotSquared (PlotSquared (Version: 2.11.27))

Here is an image of the issue: http://prntscr.com/7qai89
Here is our PlotSquared config: http://pastebin.com/MvWWGM47
Here is our plugin list: http://prntscr.com/7qb966
Here is our spigot version: http://prntscr.com/7qb9ds
Here is our server log: http://pastebin.com/PAP7MuYt

Thanks
-James

(NOTE: The second time it happened, repairs were made to the area, we came back today and the same area had the issue again. We ran a backup of the world through a chunk fixer and the  world passed.)

**Comment by boy0001** [comment]
It is an issue with the chunk being corrupt. Chunks go corrupt when the map fails to save properly (lag, crash, old hard drive). This is not an easily replicable issue, and I am unable to determine the exact source of the chunk corruption. 

As such, I would suggest going to those areas with mcedit and deleting the affected chunks. I would also suggest killing all entities in the world e,g, with `/killall`.

If you believe that the issue can be replicated in a testing environment, please let me know the steps required and I will do my best to investigate this further.
