### ISSUE TITLE
getPlotWorld issue in API?

### ISSUE THREAD

**Issue by diecode** [IntellectualCrafters/PlotSquared#381]
Hi,

I changed the PlotSquared to latest build, and my plugin break when I start the server.

My "old" method is:

```java
Bukkit.getServer().getWorld(plotAPI.getPlotWorlds()[0]);
```
Now, it is returning null, so I checked other methods:

```java
PS.get().getPlotWorlds()
``` 
and 
```java
PlotSquared.getInstance().getPlotWorlds()
``` 

are returning null or empty array too. I cannot get PlotWorld. Is this my fault or can you reproduce it?

My plugin yml is:

```yml
depend: [PlotSquared, Vault, Multiverse-Core]
```

**Comment by boy0001** [comment]
When are you trying to check for plot worlds, would this be during startup before the worlds are loaded?

**Comment by boy0001** [comment]
Cannot replicate, please respond if you would like this ticket reopened.
