### ISSUE TITLE
A setblock timer is bound to either the current plot or you.

### ISSUE THREAD

**Issue by Dragon79mx** [IntellectualCrafters/PlotSquared#383]
When I try to delete or clear some plots I get this message 
A setblock timer is bound to either the current plot or you.

What is this?

**Comment by boy0001** [comment]
When you queue up another action such as pasting a schematic, setting the floor, it will prevent you from doing another action to that plot.

If you are not doing anything else, please make sure you are using PlotSquared 2.12.4 or greater and let me know and I will investigate this further.
