### ISSUE TITLE
error on startup 

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualCrafters/PlotSquared#387]
http://hastebin.com/ayogabehej.avrasm

**Comment by boy0001** [comment]
Error with echopet:
> Error occurred while enabling EchoPet v2.8.1-SNAPSHOT-b61 (Is it up to date?)

**Comment by PhanaticD** [comment]
But it only happened after updating this plugin, it happened on my other server to but with mcpainter instead of echopet. Check the stacktrace
