### ISSUE TITLE
Log1x PlotMe Issues

### ISSUE THREAD

**Issue by Sauilitired** [IntellectualCrafters/PlotSquared#394]
> Hi. I'm looking to switch from PlotMe 0.17.x to PlotSquared after the recent issues with PlotMe.

> On my Development server, I have successfully migrated my PlotMe 0.17.x database to Plot2, and /plot list and /plot info work as intended showing the proper information and usernames.

> I seem to be having 2 issues though.

> 1) When attempting to /plot condense plotworld start 15000, it says "[P2] NO PLOTS FOUND" -> is this simply because there is no support for Condensing a world that was once owned by PlotMe? I haven't tried it yet, but I'm also praying I can regen the roads on a once-PlotMe world.

> 2) Not sure if this is related to the latest Plot2 release, but without having any console errors whatsoever before; it appears LibsDisguises and EchoPet are both having issues with Plot2. EchoPet crashes on start as seen [here](http://pastie.org/pastes/10290459/text?key=weflablj5foemgakaryhfq) and LibsDisguises throws an error everytime a player enters a plot as seen [here](http://pastie.org/pastes/10290465/text?key=3ejtqflok443mu9ofvxsg) as well as on start.

> Any help with these 2 above issues would be GREATLY appreciated as I'm very eager to make the switch on my live server here soon.

> Thanks a ton.
> **Log1x**

**Comment by Sauilitired** [comment]
**Related Post**: https://www.spigotmc.org/threads/plotsquared.29970/page-77#post-858608

**Comment by boy0001** [comment]
1) It should be clarified that it condenses plots outside the specified radius, which is measured in plot width. So when you use 150,000, any plot more than 150,000 plots away from the center is condensed.

2) Try updating PlotSquared, and delete the disabled.yml in the PlotSquared folder.

**Comment by Sauilitired** [comment]
Resolved by our great support team (mostly because I am awesome)
