### ISSUE TITLE
Couple more chat color inconsistancies

### ISSUE THREAD

**Issue by Log1x** [IntellectualCrafters/PlotSquared#397]
Hi. Reporting a couple more inconsistencies with chat coloring. This list may be expanded on as I do configuration, so I will continue to update this Issue until it is assigned.

![Plot Flags](http://log1x.com/screenshots/2015-07-13_22-15-32.png)
/p set flag needs to use the style.yml colors.

![Plot Comments](http://log1x.com/screenshots/2015-07-13_21-47-01.png)
%amount% doesn't appear to be working as well as the username color is hardcoded.

![PlotSquared](http://log1x.com/screenshots/2015-07-13_22-19-47.png)
"or" was accidentally typo'd &2 instead of $2 in the default translation file

![Debug Language](http://log1x.com/screenshots/2015-07-14_00-22-19.png)
Small typo for 'debug' on line 213 of the translation file.

![Owner Language](http://log1x.com/screenshots/2015-07-14_00-48-23.png)
%owner% for plot_info has a white-space at the beginning of it making it not uniform with the rest of the variables. Easily fixable visually in the translation file, but the variable its self might as well have that prepended white-space removed.

![/p list](http://log1x.com/screenshots/2015-07-14_01-04-19.png)
/p list's Possible Values return doesn't seem to be translatable.

![/p list 2](http://log1x.com/screenshots/2015-07-14_01-07-10.png)
Above is the closest value I can find, but it does not seem to affect it.

![whitespace](http://log1x.com/screenshots/2015-07-14_01-19-54.png)
Line 69 'no_plot_inbox' has an extra white-space.

<3

**Comment by Sauilitired** [comment]
Fixed:

* Flag List Colours
* "or" typo
* debug_header typo
* no_plot_inbox whitespace

For the list values, the argument list is based on your permissions. 
I couldn't find the info owner whitespace issue.
