### ISSUE TITLE
Piston bug

### ISSUE THREAD

**Issue by boy0001** [IntellectualCrafters/PlotSquared#4]
pistons allow pushing blocks outside your plot if ticking "fast enough"

(This is an issue with bukkit itself, but there might be a hacky solution to this)

**Comment by boy0001** [comment]
It is as fixed as it's going to get as of: a6cd41fcb8b4f58a806d1ff8590014edc8f116ca

**Comment by dextonanderson** [comment]
This is still broken as of release 2.8.3

**Comment by boy0001** [comment]
I remember testing this recently. Is there any specific trick to moving the blocks, or is it just plain broken? Also, would you happen to be using spigot for 1.8.3?

**Comment by dextonanderson** [comment]
I am using the latest build of 1.8, not 1.8.3. Just using a sticky piston and a redstone block does the trick for me.

**Comment by dextonanderson** [comment]
Still broken as of 2.8.8

**Comment by boy0001** [comment]
Fixed. See: 20d64508a59cccd2fff7934e1f84e3a264e3fe7d
