### ISSUE TITLE
Config nulling when PlotMe uuid-caching is true but conversion is false

### ISSUE THREAD

**Issue by Log1x** [IntellectualCrafters/PlotSquared#401]
You guys already know this bug, but thought I'd log it here since there was no issue created for it.

Having PlotMe uuid-caching set to true while conversion is set to false causes the plotworld configuration in config.yml to null on restart effectively making plots unusable.

http://pastie.org/pastes/10290617/text?key=qqpn0qam1vuoafvdidwgw is a paste of the config after being nulled.

<3

**Comment by Sauilitired** [comment]
```java
Settings.CONVERT_PLOTME || Settings.CACHE_PLOTME
```

Should that really be an OR? ;3

**Comment by boy0001** [comment]
Yes, the converter will run if you have the caching, but will terminate before changing anything if conversion isn't enabled.
Fixed in 4711c7c8ab813259a11de13a1132f2fb646458e7
