### ISSUE TITLE
Economy not working

### ISSUE THREAD

**Issue by Lubenica** [IntellectualCrafters/PlotSquared#65]
Hello,
Economy is not working for me. I have the latest version of PlotSquared and have Vault. I do not get any errors in the console, it just does not work. Can you look into it please?
Many thanks! :)

**Comment by xion87** [comment]
you have enalbed in the config?

**Comment by Lubenica** [comment]
Yes I have.

**Comment by xion87** [comment]
strange for me is working, you are using 1.8?

**Comment by Lubenica** [comment]
Yes, I am using 1.8.

**Comment by xion87** [comment]
you got latest vault?

**Comment by Lubenica** [comment]
Yes I do.

**Comment by xion87** [comment]
i didn't tested it with 1.8...

**Comment by xion87** [comment]
can i see your config?

**Comment by Lubenica** [comment]
My settings.yml: http://pastebin.com/ejavUYFk
PlotSquared version: 2.4.4
Vault version: 1.5.0-b28

**Comment by xion87** [comment]
you tried to upgrade to 2.5.2?

**Comment by Lubenica** [comment]
No I haven't. Should I? Because I see that no changes have been made regarding the economy.
Thanks!

**Comment by xion87** [comment]
http://www.spigotmc.org/resources/plotsquared.1177/update?update=9246
- Verified that economy still works

**Comment by Lubenica** [comment]
I will try it now and report back in 5 mins. Thank you!

**Comment by xion87** [comment]
wait a second
can you chek your yaml
      use: true
      prices:
        claim: 250000.0
        sell: 125000.0
        merge: 100.0
that is setted like this?

**Comment by Lubenica** [comment]
It's like this:
    economy:
      prices:
        merge: 100.0
        sell: 75.0
        claim: 7000.0
      use: true

I attacked the pastebin link to my settings.yml in my previous comment.

**Comment by xion87** [comment]
yeah i noticed the space are correct... so try to upgrade as i told...
anyway with latest new version i got home issue, player can't teleport to home

**Comment by Lubenica** [comment]
Tested with 2.5.2 and got the same bug. I type /plot auto and get the plot for free. Do I need to give some permission to players to activate the economy system?

**Comment by xion87** [comment]
which economy you have?

**Comment by Lubenica** [comment]
Essentials

**Comment by boy0001** [comment]
Nice comment chain.

@Lubenica 
I solved the issue, and also figured out why it was only effecting you. Try the file below to fix the issue.

@xion87
The plot home error was caused by you having claimed plots in a world that is no longer a plotworld. During startup you should see a message similar to
```
[WARNING] Found 49021 plots in DB for non existant world; 'world'.
[WARNING] - Please create the world/s or remove the plots using the purge command
```
You can either purge these plots, create the world, or use the file below which will skip invalid plots.

DOWNLOAD:
http://plotsquared.empcraft.com/PlotSquared.jar

**Comment by xion87** [comment]
@boy0001 
yeah i have that error but is because i use the same database both for plot server and creative server....

**Comment by Lubenica** [comment]
@boy0001 thank you very much, I will try the new version! Could you explain me please why was it only affecting my server?

**Comment by boy0001** [comment]
Vault was loading after the plugin tried to establish the economy hook. I can't imagine you were the only one experiencing the issue.

@xion87 
Are you using different table prefixes for each server?

**Comment by xion87** [comment]
nope the same prefix

**Comment by xion87** [comment]
also a OT question, i run as offline mode, what you suggest to config the uuid?

**Comment by boy0001** [comment]
You could set "uuid.offline" to true in the "settings.yml" however, it should auto-detect your server setup.

**Comment by xion87** [comment]
And what about the read uuid from hard disk option?

Il 05/01/2015 16.59, boy0001 ha scritto:

**Comment by boy0001** [comment]
Leave that disabled unless you have issues with UUIDs not being cached properly.

**Comment by xion87** [comment]
ty i will try
