### ISSUE TITLE
Plot reporting

### ISSUE THREAD

**Issue by sk8er92749** [IntellectualCrafters/PlotSquared#69]
I believe it would be a good idea to add a report system, this could be useful when people find inappropriate builds,
and have a notification system like a message on join for people with the permission node.

Some command examples:

/p report {plot id} {reason} reports a plot with the reason
/p reports list {page number} a list of reported plots and who reported them
/p reports show {report #} shows the reason for reporting the plot
/p reports delete {report #} deletes a report from the list

Command output examples:
/p reports list {page number} will say:
Report #1: Plot -1;1 has been reported by {player} reason: Inappropriate (reason is brief and should have a configurable character limit
or have a list of reasons you can pick from, like Inappropriate, Useless, Other and so on)
Report #2: Plot -1;0 has been reported by {player} reason: Useless 
/p report show #1 will say: Reported by {player}: {full report details/description by player}

What do you think?

**Comment by InternetPerson** [comment]
nice

**Comment by boy0001** [comment]
This could potentially be added to the existing comment system.

**Comment by InternetPerson** [comment]
how would that work ?

**Comment by EvilOlaf** [comment]
Enhancement

Replace
/p report {plot id} {reason}
with
/p report {reason} [plot id]
or 
/p report [plot id] {reason}
and make the plot id optional so.

If you stand on someones plot and want to report it, there should be no need to add the plot id.
Depending on your choice you need of course regex comparison for either the second or the last argument ;)

**Comment by boy0001** [comment]
It's part of the comment system, so it's currently `/plot comment admin <message>` which is definitely longer than it should be. It does record the username, plot id, etc, and it's easy enough to view, so I just should add an alias or something to make the command shorter.

Currently, standing on a plot is required, although if you are denied, you would need to stand on a nearby plot, and mention the PlotId which is not desirable.

**Comment by EvilOlaf** [comment]
To be denied on a plot is the reason why I thought its useful to make the id optional to be able to add in case... :P

I don't know what exactly you mean by "its definitely longer than it should be". Did you mean the command itself? You may add shortcut aliases like 
```/p c a <message>```
for
/plots comment admin <message>```

**Comment by boy0001** [comment]
Yes, I was just referring to the command length. I'm going to remove the `high priority` thing, as the important functionality has been added.
