### ISSUE TITLE
Plot Cleaning Error

### ISSUE THREAD

**Issue by Maruf61** [IntellectualCrafters/PlotSquared#71]
after ı updated plugin (i guess from 2.4.0) I have this problem. i cant clear plot with /plot clear or /plot delete.

Here is the stacktrack

http://pastebin.com/cBrHSvri

(i installed v2.3.3 and problem has gone :S )

**Comment by xion87** [comment]
the debug clear work fine ....

**Comment by Maruf61** [comment]
i cant give to players  debug clear command.

**Comment by boy0001** [comment]
That's a very strange stacktrace... Especially given the code that is on line 692 of the PlotHelper class.

I'll do some testing right now, and see if I can replicate the issue. 

Also, the debug clear has the same restrictions as the normal clear, it just uses a different algorithm. Players will only be able to clear plots they own. The permission node is "plots.debugclear"

**Comment by boy0001** [comment]
Can't replicate.

I'll leave this open just in case I manage to figure it out, or you have some other information that may be able to help.

**Comment by boy0001** [comment]
Should be resolved now.
