### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by EvilOlaf** [IntellectualCrafters/PlotSquared#73]
http://pastebin.com/jKQ2FcUw

Maybe missing dependency in pom?

```
test@ubuntu:~/PlotSquared/PlotSquared$ mvn -version
Apache Maven 3.2.1 (ea8b2b07643dbb1b84b6d16e1f08391b666bc1e9; 2014-02-14T18:37:52+01:00)
Maven home: /usr/share/maven3
Java version: 1.7.0_65, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-openjdk-amd64/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-43-generic", arch: "amd64", family: "unix"
```

**Comment by boy0001** [comment]
You need to manually add PlotMe as a dependency.

I compiled the latest commit for you here:
http://plotsquared.empcraft.com/PlotSquared.jar

**Comment by EvilOlaf** [comment]
Begging your pardon, but it is way more interesting to build it myself.
Anyway, I added a repository and the jar, but it still won't do the trick. I have to figure it out myself I guess.

**Comment by EvilOlaf** [comment]
Aight I give up.
Other question which can be answered better I think: How to build PlotSquared without the PlotMe converter?

**Comment by boy0001** [comment]
Question 2:
 - Delete the class, and any references to it, then remove PlotMe from the pom.xml

Original question:
 - Download plotme v0.13f http://dev.bukkit.org/bukkit-plugins/plotme/files/36-v0-13f/
 - Put it in the "lib" directory within the PlotSquared project (you may need to create it)
 - Name the file "plotme-0.13f.jar"
 - Refresh maven to have it notice that the plotme jar is actually there

**Comment by EvilOlaf** [comment]
First of all thanks for the answer. Did not expect that for obvious reasons :)

Seems like I was not as stupid as I thought. Because that is what I did. The log posted above also proofs that the file exists, because when I remove or rename the plotme jar an additional warning appears and, of course, the build fails:

```
[WARNING] 'dependencies.dependency.systemPath' for com.worldcretornica:PlotMe:jar refers to a non-existing file /home/test/PlotSquared/PlotSquared/lib/plotme-0.13f.jar @ line 94, column 25
```


Re-added I get the following output. I admit I did not compare, but I am prettiy sure that it is quite similar to the paste in the initial issue report.

http://pastebin.com/Cch6fPX3

I am not sure about that, but could this be related to WorldGuard 5.9? All possible repositories for WorldGuard do not provide the requested worldguard-5.9.pom.

I will try now to build without the converter.

**Comment by boy0001** [comment]
I never heard if you had any success building the jar.

Anywho, it should be a lot easier now as PlotMe was dumped as a dependency. I was having some [difficulty](https://github.com/WorldCretornica/PlotMe-Core/blob/73440da224b4b7f655c774e683780e771ffea379/src/bukkit/java/com/worldcretornica/plotme_core/bukkit/PlotMe_CorePlugin.java#L27-30) using the PlotMe API recently, so the new converter now accesses the database directly.

Enjoy building.

**Comment by EvilOlaf** [comment]
Hey there,

nope, I was not successful building PlotSquared yet.
I gave it another shot.

And it worked :D 
Did not test the plugin ingame but the tests have passed so far.

Thanks for still looking into this.

**Comment by boy0001** [comment]
Great to hear :D
