### ISSUE TITLE
i got a big problem

### ISSUE THREAD

**Issue by osherziv** [IntellectualCrafters/PlotSquared#76]
hello when i downloaded the plugin it didn't work i downloaded the addons worldedit regions voxelsniperregions biomegenerator and i downloaded sqlibrary and i got into minecraft and the plugin didn't work and if i do /pl the plugin is in red

**Comment by osherziv** [comment]
please :( i am using plot me right now but i want plotsquared so much !!!! :(

**Comment by EvilOlaf** [comment]
This way no one can help you.
How about providing some logs or further information about your configuration?

**Comment by osherziv** [comment]
i can give log

**Comment by EvilOlaf** [comment]
So.... Where is it?

**Comment by osherziv** [comment]
i have a pannel but i cant see the log

**Comment by osherziv** [comment]
what this plugin need to work?

**Comment by osherziv** [comment]
???

**Comment by EvilOlaf** [comment]
No log, no help. Noone here has a second sight. Try to get the latest.log file and paste it to pastebin.com

**Comment by boy0001** [comment]
Please re-open once you are able to provide a server log. Even a screenshot of the startup would do. Try to provide at least some shred of information when reporting a problem.
