### ISSUE TITLE
PlotSquared worldguard integration

### ISSUE THREAD

**Issue by EvilOlaf** [IntellectualCrafters/PlotSquared#79]
http://pastebin.com/p6Vt6HWn

Well it seems to work anyway.
Sometimes streets are not properly regenerated, but could not perfectly reproduce.
WorldGuard support in PlotSquared was enabled for testing purpose.

PlotSquared 2.5.3 @ Spigot 1.8 build from 31.12.

**Comment by boy0001** [comment]
Disable worldguard hook in settings.yml

It doesn't really do much anyway.

**Comment by EvilOlaf** [comment]
I also might remember that the worldguard regions have not been deleted every time I deleted a plot. Or I just wasn't patient enough for the dynmap....

Never mind.

**Comment by EvilOlaf** [comment]
Does PS still need WG integration? The flag system seems to work pretty nicely and makes the use of WG unnecessary.

**Comment by boy0001** [comment]
okay then.
