### ISSUE TITLE
Seperate perm nodes for setup and admin bypass

### ISSUE THREAD

**Issue by EvilOlaf** [IntellectualCrafters/PlotSquared#83]
Enhancement 

To edit others plots and do stuff like add/remove/trust or setowner you need the plots.admin permission to bypass any ownership checks.

I would like to see a separate permission node to allow server-admins to build everywhere and bypass plots region and ownership checks or maybe easier to accomplish a separate node to start the setup process and the use of reload.

**Comment by boy0001** [comment]
How about sub permissions?
 - plots.admin.setowner
 - plots.admin.build
 - plots.admin.setup
 - plots.admin.reload
etc.

Then "plots.admin" bypasses all.

**Comment by EvilOlaf** [comment]
Sounds fine.
Anyway I don't need this additional subdivision but maybe some other people do ;)

**Comment by jyhsu2000** [comment]
I need these permission nodes too.
About "plots.admin.build", can you subdivide it to the following two?
- permission to build in anyone's plot
- permission to build in the road

Maybe like "plots.admin.build.anyplot" and "plots.admin.build.road".
And "plots.admin.build" includes these two.

**Comment by boy0001** [comment]
I could potentially subdivide it even more, it just takes time.

As for the hierarchy, the only permission group will be plots.admin (which will include everything).
Anything else you can just use the magic star
e.g. 
 - plots.build.*
Will include plots.build.road, plots.anyplot.plot etc.

**Comment by jyhsu2000** [comment]
Thanks.
I will expect for it.

**Comment by boy0001** [comment]
Don't expect too hard, you might hurt yourself.

I'm going to be busy for the next 2 weeks, so if I don't add the feature tomorrow, it will need to wait until I next have some free time.

**Comment by EvilOlaf** [comment]
Take all the time you need :D

**Comment by boy0001** [comment]
== New permissions.
EVENT STUFF
plots.admin.build.road
plots.admin.build.unowned
plots.admin.build.other

plots.admin.destroy.road
plots.admin.destroy.unowned
plots.admin.destroy.other

plots.admin.interact.road
plots.admin.interact.unowned
plots.admin.interact.other

plots.admin.projectile.road
plots.admin.projectile.unowned
plots.admin.projectile.other

plots.admin.pve.road
plots.admin.pve.unowned
plots.admin.pve.other

COMMAND STUFF
plots.admin.command.schematic
plots.admin.command.clear
plots.admin.command.copy
plots.admin.command.debugclear
plots.admin.command.delete
plots.admin.command.denied
plots.admin.command.helpers
plots.admin.command.kick
plots.admin.command.merge
plots.admin.command.paste
plots.admin.command.reload
plots.admin.command.set
plots.admin.command.setowner
plots.admin.command.setup
plots.admin.command.swap
plots.admin.command.trusted
plots.admin.command.unclaim
plots.admin.command.unlink

**Comment by EvilOlaf** [comment]
That's hugh :D

**Comment by boy0001** [comment]
Wasn't that the idea?
