### ISSUE TITLE
Web Interface 500 error?

### ISSUE THREAD

**Issue by fillefilip8** [IntellectualCrafters/PlotSquared#85]
The web interface is blank when i go to the page.
Also your website http://www.intellectualsites.com/ is down.

**Comment by boy0001** [comment]
What is your version of PHP. It's possible that an old version of PHP is not adequate to run the web interface.

**Comment by boy0001** [comment]
Figured out the issue (finally)
 - The problem should be resolved with the latest download of the web interface.
