### ISSUE TITLE
Add unclaim all empty plots command.

### ISSUE THREAD

**Issue by Uncleleech** [IntellectualCrafters/PlotSquared#92]
This'll be handy for cleaning plots with no blocks changed or less than a supplied number.

Perhaps /p prune?

Could also include a time.

Thanks,
Thomas Carroll

**Comment by boy0001** [comment]
https://github.com/IntellectualCrafters/PlotSquared/blob/master/PlotSquared/src/main/java/com/intellectualcrafters/plot/commands/Trim.java

Use /plot trim

**Comment by Uncleleech** [comment]
Perhaps, we can improve command documentation to include this. It really isn't clear.

**Comment by boy0001** [comment]
Yeah, I'm really terrible with documentation.

**Comment by Uncleleech** [comment]
Could you either, make the github wiki contributable etc. or source other
people to do it for you? eg. me (:p)

Thanks,

Thomas Carroll
tcarroll@unclelee.ch
http://unclelee.ch/

**Comment by boy0001** [comment]
You should be able to contribute now.

**Comment by Uncleleech** [comment]
Do you want end-user or command on there? I'd suggest making a commands / perms table esp. as this is indexed before your site.
