### ISSUE TITLE
Plot protection system

### ISSUE THREAD

**Issue by EvilOlaf** [IntellectualCrafters/PlotSquared#94]
```
Enhancement

Another well known and quite similar plot management plugin offers in this configuration to define which blocks or items like buttons or levers are protected on plots and which are public accessible.

I really liked this feature because for example you could make buttons made from wood usable for everyone meanwhile stone buttons can only be used from authorized players. So there could be public and private areas.

Another example would be chests and trapped chests. If players want to have a shared chest with everyone on the server without having added each and every player to a  plot there could be trapped chests unprotected and common chests protected.

Maybe you wanna give this feature a chance. I would love to see that :).
```

```
Enhancement

Users which have no helper or trust status on a plot can not use quickshop chests to buy or sell items. Pex debug tells me that the plugin asks for plots.admin.interact.other which is obviously not present on common players without any special rights.

Therefore QuickShops cannot be used in a Plotworld seriously.

It would be very nice if this could be fixed.

Maybe this could be combined with #94
```

**Comment by EvilOlaf** [comment]
Awesome

**Comment by boy0001** [comment]
The flag system has just been overhauled so it supports a huge range or flag types (previously it just had strings). The flag system will be used to manage the plot protection (you can set default flags in the config).

The reason for this overhaul is efficiency; having to parse a flag every time you want to check if a block interaction is allowed, might cause minor lag.

In the next few updates, the current protection flags will be removed and replaced with much cleaner and easier to manage ones:
 - place : blocks allowed to be used
 - break : blocks allowed to be placed
 - use : blocks allowed to be interacted with
Boolean flags:
 - pvp:
 - pve:
 - mob-interact
 - vehicle-place
 - vehicle-use
 - vehicle-break

Are there any other flags you can think of?

**Comment by EvilOlaf** [comment]
Looks nice.

Pretty good question, have to think about it =).
Maybe I’ll come up with something later.

**Comment by EvilOlaf** [comment]
Will server owners be able to determine which flags users can set?
Or alter to set a permission node for each flag?

**Comment by boy0001** [comment]
There's already a permission node per flag
"plots.set.flag.<flag>"

**Comment by EvilOlaf** [comment]
How would setting an individual use flag permission for example look like? 69 for leaver and 143 for wooden button
```
plots.set.flag.use.69,143 ?
```

Oh by the way. Remember https://github.com/IntellectualCrafters/PlotSquared/issues/81 ?
I actually don't know how the plugin works respectively what the trigger for a protected animal/npc is, but maybe this also could be merged into flags too.

**Comment by boy0001** [comment]
The following flags have been added:
 - explosion  
 - hostile-interact
 - hostile-attack
 - animal-interact
 - animal-attack  
 - tamed-interact
 - tamed-attack        
 - misc-interact      
 - hanging-place
 - hanging-break      
 - vehicle-use
 - vehicle-place
 - vehicle-break     
 - place
 - break
 - use

If it's not extensive enough, I can always add more as the current system is quite easy to modify.

**Comment by EvilOlaf** [comment]
This may be a stupid a question but on default there should be no flags enabled on any plot.
So the only persons who could damage an animal are the trusted, helpers and the plot owner himself. Is that correct?

**Comment by boy0001** [comment]
That should be correct. You can change the defaults in the settings.yml however.

**Comment by EvilOlaf** [comment]
Absolutely awesome.
Can't wait for a stable release :D

**Comment by EvilOlaf** [comment]
Some other basic worldguard flags would be nice like ice-melt or ice-form. So individuals could build houses from common ice blocks.
