### ISSUE TITLE
Roadschematics

### ISSUE THREAD

**Issue by AgentLV** [IntellectualCrafters/PlotSquared#96]
Hello, I'm having problems with creating roadschematics, not quite sure what I'm doing wrong.

This is how the world looks standardly:
http://abload.de/img/2015-01-17_12.46.06jvx69.png

Then I change the road and create the schematic:
http://abload.de/img/2015-01-17_12.46.131baj7.png

Then I enter /plot RegenAllRoads and get this:
http://abload.de/img/2015-01-17_12.46.47pay0t.png

**Comment by boy0001** [comment]
Temporary fix until the next release:
 - Change your road width to an odd number e.g. 7 or 9

**Comment by boy0001** [comment]
Fixed in: 41d3283bbb1c4c6747e42a00efe261e1f3e3ce68
