### ISSUE TITLE
Helper * (restart)

### ISSUE THREAD

**Issue by baticag** [IntellectualCrafters/PlotSquared#97]
When I do /plot helpers add * to a plot, on next restart noone can build. (I want everyone can build on that plot)

This is still not fixed (even if you said it was on spigot)

**Comment by boy0001** [comment]
I verified that the problem was fixed before. What version are you using of PlotSquared?

**Comment by baticag** [comment]
Newest version on spigot 2.5.10
Here's the video: http://youtu.be/BqCHG0mHHe0
Using MySQL and server is in offline mode

I also found a some bugs in console when I do the command /plot hp add *
http://pastebin.com/dVT2WSeP
http://pastebin.com/UepiB2sm

**Comment by boy0001** [comment]
Try the latest version. If it fixes the issue, you can close this.

**Comment by baticag** [comment]
Working great! Thank you so much! :+1:
