### ISSUE TITLE
Translation file reset

### ISSUE THREAD

**Issue by boy0001** [IntellectualCrafters/PlotSquared#98]

**Comment by boy0001** [comment]
`I modify translation file when server run.
I use /plot reload and get message [Plot]The translation files has been reloaded.
But it doesn't take effect.
And when I stop server, the translation file auto restore to the version when I startup server.`

**Comment by EvilOlaf** [comment]
This couldn't be fixed in 2.6 already? :/

**Comment by boy0001** [comment]
I'm waiting on citymonstret to fix this.

**Comment by EvilOlaf** [comment]
Has this issue been fixed? 
Related to https://github.com/IntellectualCrafters/PlotSquared/issues/154

**Comment by boy0001** [comment]
I could always edit the translations without any problems, so I have no idea if the people experiencing the issues still have the same problem.

**Comment by boy0001** [comment]
I'll just assume it's fixed as I haven't heard any complaints recently. It will be reopened if issues surface.

**Comment by Heron4gf** [comment]
Wait i'm having same issue, using an official translation, italian one
