### ISSUE TITLE
Could not pass event PlayerTeleportEvent to PlotSquared

### ISSUE THREAD

**Issue by mariolars** [IntellectualCrafters/PlotSquared#99]
When somebody is teleporting on plot map the strange error appears. 
http://pastebin.com/DXF554zC
http://pastebin.com/dfGcMRqi

Plugins: WorldEdit, SimpleNoDrop, SpawnTP, MultiWarps, ClearLag, PluginManager, ChatControl, BanManager, BadPotion, MultiWorld, IPWhitelist, Stargate, AntiRS, cShortcut, TeleportSuite, PermissionsEx, Microblocks, SimpleNoPickup, Vault, HideStream, AZRank, NoItem, PlotSquared, Marriage, ColoredTags, ChestCommands.

Spigot version:
CraftBukkit version git-Spigot-1.7.9-R0.2-207-g03373bb (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)

**Comment by boy0001** [comment]
Check your translations file, you might have an invalid color specified:
"title_entered_plot_color"
or
"title_entered_plot_sub_color"

Specifically "ZLOTY" is not being recognized as a valid color.
